### PR TITLE
Preparing the Activity Stream release 1.7.0

### PR DESCRIPTION
**Pull request by ncloudioj**
Hi all,

We are now preparing the release of A-S 1.7.0. The add-on has been made available at [pre-release channel](https://moz-activity-streams-prerelease.s3.amazonaws.com/dist/latest.html). Please install it, test it, and leave the feedback, bug reports, and other inputs in this thread.

# Release checklist
- QA
  - [x] @pdehaan 
  - [x] @SoftVision
- Product
  - [x] @nchapman 
  - [x] @aaronrbenson 
- Engineering
  - [x] @tspurway 
  - [x] @jennchaulk 

Please use the `release/block` or `release/uplift` to label the bug reports as well as other release related issues. Once you finish the review, please check off the corresponding item in the above checklist.

*Note*: checking off the item may not work, you can either modify it in place (i.e modify `[ ]` to `[x]`), or just drop a good old `r+` comment below.

*Note*: release highlights and the changelog will be attached shortly.

Thanks

### CODE REVIEW

**Comment by jaredkerim** [comment]
I am uplifting the following commits for this release:

https://github.com/mozilla/activity-stream/commit/82ed3ec22d4b49d3fec42ff6bf8f31358004952c

https://github.com/mozilla/activity-stream/commit/9cbdd63e75c6bfebc7665c3327a06a55ba6fbb68

https://github.com/mozilla/activity-stream/commit/682e688e9f45577b869bf32b6cdc3fbe4d3baa89

**Comment by jaredkerim** [comment]
Also uplifting this: https://github.com/mozilla/activity-stream/pull/2271/commits/40ba21eaec282a8a97f99165f771b38af21d796d

**Comment by rlr** [comment]
I've uplifted 40ba21eaec282a8a97f99165f771b38af21d796d just now

**Comment by ncloudioj** [comment]
Uplifting various telemetry commits:

* f1b80c0
* f5b4a1b
* 932226c

**Comment by ncloudioj** [comment]
Making the release now.

**Comment by ncloudioj** [comment]
V1.7.0 is now going live.

**Pull request closed without merging**
