### PR TITLE
fix (travis): fix tests. return promise from mock asyncFetchLinks()

### PR DESCRIPTION
**Pull request by rlr**
let's see if travis likey.

### CODE REVIEW

**Comment by rlr** [comment]
@ncloudioj @piatra I commented out the test that intermittently fails and it seems happy (so far). Thoughts?

**Comment by dmose** [comment]
If the test is truly failing intermittently and we don't have time to fix it now, leaving it on starts breaking our trust in our tests, which leads to a fair bit of pain.

I'd strongly vote for fixing the failure now, but if that's really impractical, then there's a lot to like about disabling it, maybe using it.skip() and a comment, and filing another bug to fix it.

**Comment by ncloudioj** [comment]
Agreed. I am trying to fix this test failure now, since I believe this test is necessary in general.

**Comment by as-pine-proxy** [comment]
[Treeherder: 36a0061173508590330789fd14c8e71ecab0a371](https://treeherder.mozilla.org/#/jobs?repo=pine&revision=36a0061173508590330789fd14c8e71ecab0a371)

**Pull request merged**
