### PR TITLE
Fix Bug 1421422 - Collect "region" and "profile_creation_date" for AS

### LINKED ISSUE #3876: Collect "region" and "profile_creation_date" for AS
This is just a clone of the Pingcentre bugs [#111](https://github.com/mozilla/ping-centre/issues/111) and [#117](https://github.com/mozilla/ping-centre/issues/117). The code change has already been merged. We just need to update the document of AS, and finish the data review here.

### PR DESCRIPTION
**Pull request by ncloudioj**
This closes #3876

### CODE REVIEW

**Comment by ncloudioj** [comment]
@fmarier This only contains the document update for the change, I've already merged the patch before the data review (oops). We can further tweak the code patch if we find anything here.

Thanks!

**Comment by fmarier** [comment]
I've started a thread with Marshall. Given Thanksgiving in the US, it may be a little while because I can respond.

**Comment by ncloudioj** [comment]
@fmarier Thanks! 

Just notice you've being also involved in this bug https://bugzilla.mozilla.org/show_bug.cgi?id=1419788 , hope that's easier for you to get more context on this.

**Comment by fmarier** [comment]
How is the search region determined? Is it based on IP address geolocation? Do we set it to the exact country code or do we filter / group countries in any way?

The reason I'm asking is to figure out whether or not it can be considered Category 1.

**Comment by ncloudioj** [comment]
@fmarier Not sure how exactly it's determined, I guess the Search team knows more detail about that. AS simply records the current value (as of the telemetry gets generated in Firefox) of pref "browser.search.region", which is exactly the same as what we have collected in https://bugzilla.mozilla.org/show_bug.cgi?id=1419788. So I suppose this should be of the same Category as the one in bug1419788.

**Comment by fmarier** [comment]
Thanks, I pinged Javaun about it.

**Comment by ncloudioj** [comment]
Hey @fmarier, any updates on this? If you have any other questions, feel free to reach out :)

**Comment by fmarier** [comment]
I'm still trying to find someone who can answer my [questions about the search country](https://github.com/mozilla/activity-stream/pull/3877#issuecomment-347264615). Haven't had any luck yet.

**Comment by ncloudioj** [comment]
@fmarier I think :mconnor can answer that question. Could you try reaching out to him please?

**Comment by fmarier** [comment]
Based on an email thread with mconnor, I have escalated this to @rjweiss and Marshall. @rjweiss will follow up with you once they have found a solution.

**Comment by ncloudioj** [comment]
@fmarier Thanks for the update!

**Comment by ncloudioj** [comment]
1. What questions will you answer with this data?
  * profile_creation_date: to understand the age of Activity Stream users' profile, which allows us to identify the new users and existing users among different Firefox versions.
  * region: to investigate certain geo related issues, for instance, the top stories feature was disabled if the region was unset or unknown. 

2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
This helps us understand if current user regions are set correctly, which improves the overall quality of recommendation content in Activity Stream. 

3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
There is no current instrumentation of this important value. 

4. Can current instrumentation answer these questions?
There is no current instrumentation of this important value.

5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories on the found on the Mozilla wiki.
  * profile_creation_date is of category 1
  * region is of category 2 data (information about where the user’s machine sits). It is most similar to locale, in that it is a vague geo preference that does not leak the user’s location. However the measurement of region is a different one from locale, and region is used in important features in Activity Stream like Top Stories.

6. How long will this data be collected? Choose one of the following:
Permanently.

7. What populations will you measure?
All Firefox channels, all countries ,all locales. 

8. Please provide a general description of how you will analyze this data.
General reporting on Redash. 

9. Where do you intend to share the results of your analysis?
This is shared over Mozilla LDAP via Redash.

**Comment by ncloudioj** [comment]
Hey @rjweiss @fmarier , I've attached the data review form above, could you r? it, please?

**Comment by fmarier** [comment]
How granular is the region code? Is it the country code like the one we have for search?

**Comment by Mardak** [comment]
The region code is the one from browser.search.region so the same value used for search.

**Comment by fmarier** [comment]
> The region code is the one from browser.search.region so the same value used for search.

Ok thanks. I haven't heard back from Marshall yet. He was working on this part with the search team to see if we can filter the countries. Once that's been resolved, we can carry on with the data review.

**Comment by fmarier** [comment]
To be clear, there's nothing wrong with the creation date since that's definitely in category1/2 territory. If you wanted to land that quickly, we could split it off from the region code and land it separately.

**Comment by ncloudioj** [comment]
Hey @fmarier, any updates from the legal for the `region` collection? This is one of the P1 features for the next AS release, and given the Firefox 59 code freeze will be happening in days, could you keep us posted so that we can decide what's next accordingly. Thanks!

**Comment by ncloudioj** [comment]
Merge and close this as the data reviewed was already done at 

https://bugzilla.mozilla.org/show_bug.cgi?id=1421422

**Comment by as-pine-proxy** [comment]
[Treeherder: 9cb355e5ad9809083f7afe3ad7a234770948fe8b](https://treeherder.mozilla.org/#/jobs?repo=pine&revision=9cb355e5ad9809083f7afe3ad7a234770948fe8b)

**Pull request merged**
