### PR TITLE
Bug 1511152 - adding lint:jsx-a11y script to be able to run jsx a11y …

### PR DESCRIPTION
**Pull request by yzen**
…rules independently.

This is a proposal of how to not be too disruptive but also flag a11y issue found with this tool.

### CODE REVIEW

**Comment by yzen** [comment]
@k88hudson this was the sort of thing I was talking about before the all-hands.

**Comment by Mardak** [comment]
@k88hudson we might be able to turn this on for just trailhead to start ?

**Comment by yzen** [comment]
@Mardak , @k88hudson Just one thing I'd recommend, since it's still hopefully early in the process, to remove the custom rules I added (that change error to warn level) and use the defaults.

**Comment by k88hudson** [comment]
Hey, sorry this ended up getting lost in my queue – what still needs to be done with this one to merge / what has ed's patch covered v.s. what is still left? @yzen @Mardak?

**Comment by Mardak** [comment]
The "only" thing to do is to run the jsx-a11y on more files instead of just Trailhead related stuff:
https://github.com/mozilla/activity-stream/blob/84543b06c76c16778acbde1110288cde7c56e566/yamscripts.yml#L67

**Comment by k88hudson** [comment]
I'm closing this and filing new bugs under https://bugzilla.mozilla.org/show_bug.cgi?id=1511152 (which is now a meta bug) to expand coverage, our intern @AllegroFox will be working on them

**Pull request closed without merging**
