### PR TITLE
fix(systemaddon): Closes #2918 Reuse check.svg from firefox

### LINKED ISSUE #2918: Broken build: duplicate glyph-check-16.svg and browser/chrome/browser/skin/classic/browser/check.svg
#2909 added the glyph-check-16.svg file and the build doesn't like it because it's the same as https://searchfox.org/mozilla-central/source/browser/themes/shared/icons/check.svg
```
ERROR: The following duplicated files are not allowed:
INFO -  browser/features/activity-stream@mozilla.org/chrome/content/data/content/assets/glyph-check-16.svg
INFO -  browser/chrome/browser/skin/classic/browser/check.svg
INFO -  /home/worker/workspace/build/src/toolkit/mozapps/installer/packager.mk:39: recipe for target 'stage-package' failed
```

### PR DESCRIPTION
**Pull request by sarracini**
Re-use the existing check.svg so that pine can be happy again

### CODE REVIEW

**Comment by as-pine-proxy** [comment]
[Treeherder: 58faa12409fe273e163b532e629742ef20602bce](https://treeherder.mozilla.org/#/jobs?repo=pine&revision=58faa12409fe273e163b532e629742ef20602bce)

**Comment by Mardak** [comment]
This PR seems to be the first that has tests failing due to network requests:
https://treeherder.mozilla.org/#/jobs?repo=pine&revision=58faa12409fe273e163b532e629742ef20602bce&filter-classifiedState=unclassified&filter-resultStatus=testfailed&filter-resultStatus=busted&filter-resultStatus=exception&selectedJob=116029827
```
 GECKO(17356) | FATAL ERROR: Non-local network connections are disabled and a connection attempt to example (52.34.31.151) was made. [log…] 
```
https://treeherder.mozilla.org/logviewer.html#?job_id=116029827&repo=pine&lineNumber=4269

**Comment by Mardak** [comment]
I've repushed the commits that failed to build because of the #2909 bustage to try to see if one of them introduced the network request failure.

For my own notes: `pushd ../activity-stream/ && git rh head && git co head~1 && git sh 4af08ab | git apply && npm run buildmc && popd && git fetch ../activity-stream/ HEAD && git add browser/extensions/activity-stream/ && git caa -C fetch_head && git push pine`

**Comment by Mardak** [comment]
Oh ha. Somehow `example` hostname became an actual hostname ? Bugzilla says it's fixed: https://bugzilla.mozilla.org/show_bug.cgi?id=1382858

**Pull request merged**
