### PR TITLE
Fix Bug 1438523 - add enableWideLayout to prerender prefs

### PR DESCRIPTION
**Pull request by rlr**
The "wireframe" term threw me off but I eventually figured it out.

### CODE REVIEW

**Comment by rlr** [comment]
Hmm, I thought the issue was that we flash 6 topsites then change it to 8. Also the search bar starts at one size then grows. `.section-empty-state` only applies to sections?

**Comment by rlr** [comment]
Yeah, I dont think `.section-empty-state` has anything to do with the screenshot on the bug:

**Comment by rlr** [comment]
(ie, the issue, as I see it, is that we load the page with the `div.wide-layout-disabled` and then remove the class once react renders`

**Comment by Mardak** [comment]
That video also shows the smaller placeholder highlights outline becoming big.

**Comment by rlr** [comment]
Is that ^^ what you are referring to?

**Comment by rlr** [comment]
fancy screenshots! how you get those magical powers? ha

**Comment by Mardak** [comment]
For the screenshot, I ended up doing screen recording to get the exact frame then some image editing (ended up using ScreenFlow and GravitDesigner, but any recording and editing should do)

**Comment by as-pine-proxy** [comment]
[Treeherder: 2cf0e0f5a4f57f8b4992829118f66caec8b6072c](https://treeherder.mozilla.org/#/jobs?repo=pine&revision=2cf0e0f5a4f57f8b4992829118f66caec8b6072c)

**Pull request merged**
