### PR TITLE
chore(build): Read pocket api key from ENV

### PR DESCRIPTION
**Pull request by k88hudson**
This patch allows us to pick up an API key from `process.env` for pocket

### CODE REVIEW

**Comment by k88hudson** [comment]
Whoever has time to review

**Comment by jaredkerim** [comment]
I think we decided that we will store the API key in the proxy the way we do now, so the client doesn't need to know the API key.

**Comment by k88hudson** [comment]
@jaredkerim happy to refactor next week, but is it cool if we just do this for now so dev will work?

**Comment by jaredkerim** [comment]
@k88hudson yep sounds good!

**Comment by as-pine-proxy** [comment]
[Treeherder: aef161d199fcee3b8e5b2fb6fb7eb5a45cb822f9](https://treeherder.mozilla.org/#/jobs?repo=pine&revision=aef161d199fcee3b8e5b2fb6fb7eb5a45cb822f9)

**Pull request merged**
