### PR TITLE
chore(lint): Switch to eslint-plugin-mozilla/recommended@0.2.40

### LINKED ISSUE #2229: Enable eslint for system-addon/
Right now we don't have eslint targeting `.jsm`s. There are a few issues we would need to sort out (like `no-unused-vars` conflicting with jsm-style exports, for example) to get this to work

### PR DESCRIPTION
**Pull request by Mardak**
Fix #2229. Update the dependency and clean up linting issues and duplicate config.

@Standard8 One oddness I'm running into right now is that I needed to `ln -s ../mozilla-central/tools/` as `convertWorkerExpressionToGlobals@lib/helpers.js` is looking for `modules.json`. Other than that, I was able to `npm install tools/lint/eslint/eslint-plugin-mozilla` from `activity-stream` to develop against `0.2.32`

### CODE REVIEW

**Comment by Mardak** [comment]
Oh duh. I now see https://bugzilla.mozilla.org/show_bug.cgi?id=1347709 re: `modules.json`

**Comment by Standard8** [comment]
Yeah, that's next on my list of things to fix. Probably will be next week, but hopefully will make it much more usable.

**Comment by Mardak** [comment]
I'll be updating the PR to use the just published 0.2.40 and fix the not-linting-`.jsx` issue noted in #2427

**Comment by Mardak** [comment]
That's odd.. `includes` existing is checked but then turns out to not be a function?
```
browserWindowEnv.browserjsScripts.includes is not a function
TypeError: browserWindowEnv.browserjsScripts.includes is not a function
    at EventEmitter.Program (/home/travis/build/mozilla/activity-stream/node_modules/eslint-plugin-mozilla/lib/rules/import-browser-window-globals.js:31:45)
```

**Comment by Standard8** [comment]
> That's odd.. includes existing is checked but then turns out to not be a function?

Complete guess... old node version?

**Comment by Mardak** [comment]
```
$ node --version
v5.11.1
$ npm --version
3.8.6
$ nvm --version
0.33.1
```

**Comment by Mardak** [comment]
locally testing..

node v7.9.0
```
> [].includes
[Function: includes]
```

node v5.12.0
```
> [].includes
undefined
```

**Comment by Standard8** [comment]
See [bug 1346014](https://bugzilla.mozilla.org/show_bug.cgi?id=1346014) - you'll need at least 6.9.1 for the dependencies.

**Comment by Mardak** [comment]
Oh oops duh, the check isn't for `includes`, it's checking `browserJsScripts` https://dxr.mozilla.org/mozilla-central/source/tools/lint/eslint/eslint-plugin-mozilla/lib/rules/import-browser-window-globals.js#31

**Comment by Mardak** [comment]
Ha ;) `  Not enough arguments [nsIObserverService.addObserver]`

**Comment by k88hudson** [comment]
Looks good to me! Node `7.9` is in stable now, so we could just upgrade all the way to that... but if I guess `6.9` is consistent with the version Firefox requires for `eslint`

**Comment by as-pine-proxy** [comment]
[Treeherder: d1959e5a2236d5244af9ab715d2d9a82da6a9659](https://treeherder.mozilla.org/#/jobs?repo=pine&revision=d1959e5a2236d5244af9ab715d2d9a82da6a9659)

**Pull request merged**
