### PR TITLE
Preparing the release of Activity Stream 1.1.6

### PR DESCRIPTION
**Pull request by ncloudioj**
Hi all,

We are preparing the release of A-S 1.1.6. The add-on has been made available at [pre-release channel](https://moz-activity-streams-prerelease.s3.amazonaws.com/dist/latest.html), where all the release stakeholders can test and verify the add-on. That been said, we won't send a specific build as the release candidate anymore, instead, everyone should install the add-on from here during the release preview, it'll automatically update itself whenever engineer pushes bugfixes to repo.

This is our first attempt to smooth out the release process, you can see more details at [deploy.md](https://github.com/mozilla/activity-stream/blob/master/deploy.md). As usual, feedback and advises are always welcome.
# Release checklist
- QA
  - [x] @pdehaan 
  - [x] @SoftVision
- Product
  - [x] @nchapman or @aaronrbenson 
- Engineering
  - [x] @tspurway 
  - [x] @jennchaulk 

Please use the `release/block` or `release/uplift` to label the bug report as well as other release related issues. Once you finish the review on your end, please check off the corresponding item in the above checklist.

Thanks

### CODE REVIEW

**Comment by Softvision-VladBacia** [comment]
In my opinion the fix for #1605 should be uplifted to the RC build in order to improve the overall UX. It's an obvious UI issue that all users will encounter.

**Comment by ncloudioj** [comment]
Agreed! @Softvision-VladBacia  Uplifting it now.

**Comment by ncloudioj** [comment]
Uplift for #1605  is completed. Could you update your add-on and verify it? @Softvision-VladBacia

**Comment by Softvision-VladBacia** [comment]
@ncloudioj , thank you. I've checked the fix on the RC version and the issue is no longer reproducible. All work ok.

**Comment by Softvision-VladBacia** [comment]
During the testing of the AS RC version, I have observed an "issue" on the latest Firefox release 49.0.2. I've installed the AS RC on an old profile on which there were multiple older AS builds installed in the past. When I've opened a new tab, I've encountered this issue #1477 and after that I opened another New Tab. AS New Tab page was displayed with Recent Activity section although in about:config the weightedHighlights pref was set to true.

latest release
pref

**Comment by tspurway** [comment]
lgtm!

**Comment by jaredkerim** [comment]
@Softvision-VladBacia I'm unable to reproduce this issue.  Using Firefox 49.0.2 (latest) with my real history profile, if I install the release candidate, with:

extensions.@activity-streams.experiments.weightedHighlights;false

then I see old highlights and recent activity and if I switch it to


screenshot 2016-11-03 12 27 04

extensions.@activity-streams.experiments.weightedHighlights;true

then I see weighted highlights (even though it's unpopulated)

screenshot 2016-11-03 12 27 20

**Comment by jaredkerim** [comment]
@Softvision-VladBacia Oh I see, you're flipping the experiment flag, that's confusing because that should also turn weighted highlights on and off, I just tried on mine and it does in fact turn weighted highlights on and off as expected if you flip the experiment flag.

**Comment by jaredkerim** [comment]
@ncloudioj Can we please uplift this change to this release:

https://github.com/mozilla/activity-stream/pull/1720

This will allow us to collect more effective metrics for the metadata experiments.

**Comment by ncloudioj** [comment]
@jaredkerim Sure, already been uplifted. It's now fixed in the latest build

**Comment by jaredkerim** [comment]
I've added a PR to change the weighted highlights population cohort to 30% as per @emtwo direction.

https://github.com/mozilla/activity-stream/pull/1724

**Comment by jaredkerim** [comment]
@ncloudioj Can you please uplift this into the release to force weighted highlights on for everybody:

https://github.com/mozilla/activity-stream/pull/1666

**Comment by ncloudioj** [comment]
Sure, rebuilding...

**Comment by Softvision-VladBacia** [comment]
@jaredkerim , that issue was on the Fx latest release v49.0.2. Maybe something is wrong with my profile. On latest Nightly, I cannot reproduce the issue.

On the latest Fx release version, I've installed the latest AS RC build on an old profile and although the flag for weightedHighlights was automatically set to true, in the New Tab I had the "Recent Activity" area. 
As I mentioned above, on other profiles from Fx latest release and Nightly there are no issues

**Comment by Softvision-VladBacia** [comment]
Looks good from our side. Good to go.

**Comment by nchapman** [comment]
This has worked great for me this week. 👍 on release.

**Comment by jaredkerim** [comment]
@nchapman Can you check off the 'product' checkbox at the top of the PR please?  Thanks!

**Comment by nchapman** [comment]
> @nchapman Can you check off the 'product' checkbox at the top of the PR please? Thanks!

Yup. I actually did it before I added the comment 😄

**Comment by Softvision-VladBacia** [comment]
Also, #1544 should be fixed before releasing Activity Stream v1.1.6.

**Comment by jennchaulk** [comment]
checked the box!

**Comment by ncloudioj** [comment]
@Softvision-VladBacia Thanks for bringing this up! @nchapman and @aaronrbenson will be working with T-P team to update everything properly there.

**Comment by ncloudioj** [comment]
Alright, all set! Deploying A-S 1.1.6 to Test Pilot now. Will close this PR once that's done.

Thanks y'all for making this happen! 👍

**Pull request closed without merging**
