### PR TITLE
Use Photon edit icon

### PR DESCRIPTION
**Pull request by nt1m**

### CODE REVIEW

**Comment by nt1m** [comment]
It's from https://design.firefox.com/icons/viewer/#edit

**Comment by Mardak** [comment]
@aaronrbenson I guess we added edit before the photon icon was finalized?

Before:
Screen Shot 2019-04-10 at 10 09 40 PM

After:
Screen Shot 2019-04-10 at 10 08 02 PM

**Comment by nt1m** [comment]
For more context, shorlander created the icon here: https://github.com/FirefoxUX/photon-icons/pull/48

**Comment by Mardak** [comment]
Oh. Hrmm.. Looks like there's a customize icon that is closer to the existing "edit":

https://design.firefox.com/icons/viewer/#custom

**Comment by aaronrbenson** [comment]
@Mardak the icon in your "After" shot is correct. I think you're right, we didn't have that icon available to us at the time. The brush is used for Customize Mode.

**Pull request merged**
