### PR TITLE
Fix Bug 1443347 - Adjust styles for larger cards on wide layout

### PR DESCRIPTION
**Pull request by rlr**
Before:
screen shot 2018-03-06 at 8 16 07 pm

After:
screen shot 2018-03-06 at 8 31 56 pm

### CODE REVIEW

**Comment by piatra** [comment]
With the new style I hit this case where the card is cut off weirdly.
screen shot 2018-03-07 at 16 14 37571
screen shot 2018-03-07 at 16 15 22346

**Comment by rlr** [comment]
@piatra fixed that ^^

screen shot 2018-03-07 at 11 30 59 am

**Comment by rlr** [comment]
Added a tweak that @aaronrbenson requested to push up context icon/label up 4px ^^

screen shot 2018-03-07 at 11 44 40 am

**Comment by as-pine-proxy** [comment]
[Treeherder: b0ec29ba798fbcf60d8961be665152eb631f37f2](https://treeherder.mozilla.org/#/jobs?repo=pine&revision=b0ec29ba798fbcf60d8961be665152eb631f37f2)

**Pull request merged**
