### PR TITLE
Fix Bug 1428356 - dismissing/deleting Top Sites when some are pinned

### PR DESCRIPTION
**Pull request by rlr**
I removed the optimistic optimization that doesn't work right when there are pinned sites.

r? @Mardak

### CODE REVIEW

**Comment by sarracini** [comment]
I think this is fine too, it might be a tad slower since we have to wait for places to finish before blocking but we can always add other optimizations later 👍

**Comment by rlr** [comment]
thanks! Oh travis is unhappy about something /me checks

**Comment by rlr** [comment]
```
FAILED TESTS:
    SnippetsMap
      #set
        ✖ should set an item in indexedDB when connected
          Firefox 54.0.0 (Linux 0.0.0)
        Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      #delete
        ✖ should delete an item from indexedDB when connected
          Firefox 54.0.0 (Linux 0.0.0)
        expected false to be true
        AssertionError@node_modules/chai/chai.js:9320:13
        [3]</module.exports/Assertion.prototype.assert@node_modules/chai/chai.js:239:13
        [5]</module.exports/<@node_modules/chai/chai.js:1020:5
        propertyGetter@node_modules/chai/chai.js:7784:22
        proxyGetter@node_modules/chai/chai.js:9128:14
        [6]</module.exports/assert.isTrue@node_modules/chai/chai.js:4427:5
        @webpack:///system-addon/test/unit/content-src/lib/snippets.test.js:59:0 <- system-addon/test/unit/unit-entry.js:95570:7
```

Two indexedDB tests failing. Should be unrelated to these changes. Any ideas? @k88hudson ?

**Comment by rlr** [comment]
(The tests pass locally for me.)

**Comment by rlr** [comment]
After restarting travis twice, it's fixed. 🕺

**Comment by as-pine-proxy** [comment]
[Treeherder: d0e21e98f10251f47963c8b55ed477e29f7b91a8](https://treeherder.mozilla.org/#/jobs?repo=pine&revision=d0e21e98f10251f47963c8b55ed477e29f7b91a8)

**Pull request merged**
