### PR TITLE
Bump Snippets STARTPAGE_VERSION to 5.

### PR DESCRIPTION
**Pull request by glogiotatidis**
At the moment we server the same content as with startpage_version 4.

@k88hudson please r?

### CODE REVIEW

**Comment by Mardak** [comment]
Looks like a test needs to be bumped too:
`      expected { Object (snippetsURL, version, ...) } to have a property 'snippetsURL' of 'foo.com/4', but got 'foo.com/5'`

**Comment by glogiotatidis** [comment]
Tests fixed!

**Comment by k88hudson** [comment]
Awesome!

**Comment by as-pine-proxy** [comment]
[Treeherder: 665058d0f4489777e12623831ff8261d864a5a96](https://treeherder.mozilla.org/#/jobs?repo=pine&revision=665058d0f4489777e12623831ff8261d864a5a96)

**Pull request merged**
