### PR TITLE
Fix Bug 1468978 - Update schema to use format: uri for links

### PR DESCRIPTION
**Pull request by piatra**
Documentation https://spacetelescope.github.io/understanding-json-schema/reference/string.html#format

@k88hudson do you know if there's a better way to do this?
@glogiotatidis will this update to the schema help you format things on the server side?

### CODE REVIEW

**Comment by k88hudson** [comment]
`format` seems to be OK for uris, although I'm not sure how many implementations actually support it. That also won't cover the html/plain text case.

You could use `$ref` and `definitions` (it's supported, although a bit cumbersome):

```json
{
  "properties": {
    "title": {
      "allOf": [
        {"$ref": "#/definitions/plainText"},
        {"description": "Snippet title displayed before snippet text"}
      ]
    },
    "text": {
      "allOf": [
        {"$ref": "#/definitions/richText"},
        {"description": "Main body text of snippet."}
      ]
    }
  },
  "definitions": {
    "plainText": {
      "description": "Plain text (no HTML allowed)",
      "type": "string",
      "pattern": "/...../"
    },
    "richText": {
      "description": "Text with HTML subset allowed: i, b, u, strong, em, br",
      "type": "string"
    }
  }
}
```

Alternatively, we could do something non-standard, like the web extension folks do (see [this schema](https://searchfox.org/mozilla-central/source/browser/components/extensions/schemas/history.json#287) for example), which does seem a lot nicer but might not have support in a validator

**Comment by k88hudson** [comment]
If we don't care about actually programmatically validating `format`, we could also just define our own set too

**Comment by piatra** [comment]
Looking at the example linked from components/extensions `url` fields also have a plain `string` type and a `description`.

**Comment by piatra** [comment]
@k88hudson let me know if this is closer to what you had in mind.

**Comment by glogiotatidis** [comment]
> @glogiotatidis will this update to the schema help you format things on the server side?

Looks good, thanks!

**Pull request merged**
