### PR TITLE
Fix Bug 1441278 - Missing line numbers in failing unit tests

### PR DESCRIPTION
**Pull request by piatra**
WFM now

>  @webpack:///system-addon/test/unit/content-src/components/PreferencesPane.test.jsx:101:4 <- system-addon/test/unit/unit-entry.js:89146:5

### CODE REVIEW

**Comment by Mardak** [comment]
Is there a good way to fail a unit test so we don't accidentally upgrade karma again? Would checking something in `Error().stack` work?

**Comment by dmose** [comment]
Not sure if this PR is entirely analogous to the thing that caused the
Karma failure, but here is an example of something like the checking that
Ed is suggestion: https://github.com/getsentry/raven-js/pull/837/files

2018-03-06 7:19 GMT-08:00 Ed Lee <notifications@github.com>:

**Comment by piatra** [comment]
Error().stack seems to contain the non-sourced-map version of the line numbers.
Conversion seems to be done separate to running the tests https://github.com/karma-runner/karma/blob/e7b9ab89ac919eb5b4a479dfc0ce0e352d1273c7/lib/reporter.js#L10-L26

**Comment by dmose** [comment]
Maybe you could just require("karma/lib/reporter") and call the API directly to do the conversion by hand and see if it's what you want?  Maybe that's more fragile than it's worth, though...

**Comment by dmose** [comment]
I mean, really, this is only a problem until Karma 2.next gets released, and one would hope that won't be too long.  So I'm kind of inclined to say we shouldn't overrotate here.

**Comment by as-pine-proxy** [comment]
[Treeherder: b384e28030322bd94d4013ccef9a8cfb708285e3](https://treeherder.mozilla.org/#/jobs?repo=pine&revision=b384e28030322bd94d4013ccef9a8cfb708285e3)

**Pull request merged**
