### PR TITLE
chore(metadata-store): #1029 Move metadata.sqlite to the root profile directory

### LINKED ISSUE #1029: Move metadata.sqlite to root profile directory
The addon currently stores the metadata sqlite database in `local profile directory`, which is a bit confusing, as other databases such as `places` and `storage` are all located in the `root profile directory`.

### PR DESCRIPTION
**Pull request by ncloudioj**
This fixes #1029

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-stream/1032)

### CODE REVIEW

**Comment by oyiptong** [comment]
you want to delete the old file in a migration step as well

**Comment by oyiptong** [comment]
to be clear: on addon upgrade (startup load reason of `upgrade`), you want to check for the existence of the file, and possibly moving it

**Comment by ncloudioj** [comment]
Absolutely. Just wanted to drop a note for that. Because it's not easy to conduct the IO ops inside the current migration workflow. @oyiptong You just pointed out the better idea above. 👍

**Comment by oyiptong** [comment]
r+

**Pull request merged**
