### PR TITLE
Preparing the release of Activity Stream v1.3.0

### PR DESCRIPTION
**Pull request by sarracini**
Hi all,

We are now preparing the release of A-S 1.3.0. The add-on has been made available at [pre-release channel](https://moz-activity-streams-prerelease.s3.amazonaws.com/dist/latest.html). Please install it, test it, and leave the feedback, bug reports, and other inputs in this thread.

Highlights&Changelog:

* [exp] Generate top sites based on the algorithm used by the about:newtab 
* [exp] Combine frecency of the top sites of with/without www
* [exp] Fetch metadata locally
* [telemetry] Track the slow addon status in "about:performance"

Note: `[exp]` = `new experiment`

# Release checklist
- QA
  - [ ] @pdehaan 
  - [x] @SoftVision
- Product
  - [ ] @nchapman 
  - [ ] @aaronrbenson 
- Engineering
  - [ ] @tspurway 
  - [ ] @jennchaulk 

Please use the `release/block` or `release/uplift` to label the bug reports as well as other release related issues. Once you finish the review, please check off the corresponding item in the above checklist.

*Note*: checking off the item may not work, you can either modify it in place (i.e modify `[ ]` to `[x]`), or just drop a good old `r+` comment below.

*Note*: release highlights and the changelog will be attached shortly.

Thanks

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-stream/1967)

### CODE REVIEW

**Comment by rlr** [comment]
I added the following commits (sorted from newer to older) to the release-1.3.0 branch:
- 0fda037 enable screenshots experiment for 20%
- 09f50ea feat (metrics): #2063 Track `screenshot` image type in event telemetry
- e770db1 fix (addon): fixes for getScreenshots
- df79532 fix (content): #2043 hide spotlight favicon in top sites experiment
- 1690723 feat (content): #1988 new style for top sites (behind screenshots experiment)
- 37fb4c3 fix(content): Bumped tippy-top-sites for better icons
- 0c93fb7 linting fixes
- bfe614a feat(addon): #2045 Add UI to support screenshots
- 413d7bc feat(addon): #2045 Add support for screenshots
- c9f5c25 feat(metadata): Closes #2044 compute and store favicon sizes
- 84b1109 fix (content): Implement new gutter size

To enable the new awesomeness, you need to enable the experiment by setting `extensions.@activity-streams.experiments.screenshots` to `true` in about:config.

This is more or less what you should see after on the pre-release channel once it gets updated:
screen shot 2017-01-24 at 8 16 06 pm

**Comment by rlr** [comment]
2 issues filed this morning have been fixed and cherry picked:

- 8b433f9 fix(topsites): Fixes #2073 TopSites icon displayed over search suggestions
- f93670c fix (content): #2071 fix site title overflow in top sites experiment

**Comment by Softvision-VladBacia** [comment]
After running our set of tests, everything looks fine, except a few things.

**New issues found:**
#2071 - Long Website URL is not truncated and overlaps with other websites URL and Highlights section title
#2073 - Top Sites icons are displayed on top of the Search suggestion drop down
#2077 - After refreshing the AS New Tab page, "Bookmark" option is available for a previously bookmarked item from "Highlights"
#2078 - Dismissed or Deleted from History Top Sites/Highlights are displayed after page refresh

**Known issues:**
From our point of view #1544 would be nice to be resolved, as new users that want to try the experiment are shown pictures of the Timeline view (which is on hold and no longer in the add-on). Also, #2042 breaks the search functionality if the user uses the browser "Back" button to return to AS New Tab page after a refresh.
On the "Share" functionality, #1115 is still reproducible which is kind of easy to encounter in real life usage.

**Comment by Softvision-VladBacia** [comment]
Issues #2071 and #2073 were verified and are no longer reproducible.

**Comment by k88hudson** [comment]
Ok, a fix for #2079 has been uplifted

**Comment by sarracini** [comment]
The following issues were reported and are still blocking this release:
* #2084 
* #2083 
* #2082
* #2081
* #2078
* #2077
* #2076

**Pull request closed without merging**
