### PR TITLE
Rename lib/ to addon/

### PR DESCRIPTION
**Pull request by k88hudson**
I needed to do this to prevent a name collision between `lib/` and `content-src/lib/`. 

Happy to change this to another name if anyone is really against naming it `addon`

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-stream/1147)

### CODE REVIEW

**Comment by pdehaan** [comment]
Travis no like it:

```
Date: Mon Aug 22 2016 17:45:08 GMT+0000 (UTC)
Full Message: Module `addon/ShareProvider` is not found at resource://gre/modules/commonjs/addon/ShareProvider.js
Full Stack: @resource://activity-streams/addon/ActivityStreams.js:19:25
@resource://activity-streams/test/lib/utils.js:4:27
@resource://activity-streams/test/test-ActivityStreams-awesomebar-empty.js:9:44
findTests/</getNextTest@resource://gre/modules/commonjs/sdk/deprecated/unit-test-finder.js:162:25
findTests/</<.getNext@resource://gre/modules/commonjs/sdk/deprecated/unit-test-finder.js:195:32
runNextTest@resource://gre/modules/commonjs/sdk/deprecated/unit-test.js:532:14
startMany@resource://gre/modules/commonjs/sdk/deprecated/unit-test.js:546:12
findAndRunTests/<@resource://gre/modules/commonjs/sdk/deprecated/unit-test.js:27:5
Handler.prototype.process@resource://gre/modules/Promise-backend.js:933:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:812:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise-backend.js:746:11
" {file: "resource://activity-streams/addon/ActivityStreams.js" line: 19 column: 0 source: "19"}]
console.log: activity-streams: [JavaScript Error: "no element found" {file: "jar:file:///home/travis/firefox-46.0/firefox/browser/omni.ja!/chrome/browser/content/browser/aboutNetError.xhtml" line: 1}]
```

Also seeing this suspicious /lib/ JPM references in the Travis-CI logs:

```
JPM [info] .jpmignore found
...
JPM [info] Adding: /home/travis/build/mozilla/activity-stream/data
JPM [info] Adding: /home/travis/build/mozilla/activity-stream/lib
JPM [info] Adding: /home/travis/build/mozilla/activity-stream/test
...
JPM [info] Adding: /home/travis/build/mozilla/activity-stream/data/content-bridge.js
JPM [info] Adding: /home/travis/build/mozilla/activity-stream/lib/ShareManifests.js
JPM [info] Adding: /home/travis/build/mozilla/activity-stream/lib/ShareProvider.js
JPM [info] Adding: /home/travis/build/mozilla/activity-stream/test/.gitignore
...
```

**Comment by pdehaan** [comment]
Travis says:

```
console.error: activity-streams: 
  Message: Module `lib/ShareProvider` is not found at resource://gre/modules/commonjs/lib/ShareProvider.js
  Stack:
    @resource://activity-streams/test/test-ShareProvider.js:8:25
findTests/</getNextTest@resource://gre/modules/commonjs/sdk/deprecated/unit-test-finder.js:162:25
findTests/</<.getNext@resource://gre/modules/commonjs/sdk/deprecated/unit-test-finder.js:195:32
runNextTest@resource://gre/modules/commonjs/sdk/deprecated/unit-test.js:532:14
start/this.onDone@resource://gre/modules/commonjs/sdk/deprecated/unit-test.js:563:7
done/</<@resource://gre/modules/commonjs/sdk/deprecated/unit-test.js:389:31
notify@resource://gre/modules/commonjs/sdk/timers.js:40:9
```

Doing a `$ git grep '"lib/'`, I see a couple `lib/` references still, notably:

```
test/test-ShareProvider.js:const {ShareProvider} = require("lib/ShareProvider");
test/test-ShareProvider.js:const DEFAULT_MANIFEST_PREFS = require("lib/ShareManifests");
```

**Comment by k88hudson** [comment]
@sarracini ok, this should be good to go

**Comment by sarracini** [comment]
@k88hudson looks good! r+

**Pull request merged**
