### PR TITLE
fix(styles): Adjust fade in timing to avoid tart regression

### LINKED ISSUE #3568: 2.29 - 6.38% tart  (linux64, windows7-32) regression on push 2ecda1649fe43924e185445db870d7fd7e27bb0b (Wed Sep 20 2017)
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1401682

This regressed by the fading animation from #3536

### PR DESCRIPTION
**Pull request by Mardak**
Fix #3568. r?@k88hudson aaron says fix the performance issue now and adjust later
https://bugzilla.mozilla.org/show_bug.cgi?id=1401682#c4

### CODE REVIEW

**Comment by k88hudson** [comment]
Cool, still looks good!

**Comment by as-pine-proxy** [comment]
[Treeherder: 97278e47af18218477ec489509834ff3d4c96003](https://treeherder.mozilla.org/#/jobs?repo=pine&revision=97278e47af18218477ec489509834ff3d4c96003)

**Comment by as-pine-proxy** [comment]
[Treeherder: 4bd9fac2a80e0aded6035e91b66b21242071cfdd](https://treeherder.mozilla.org/#/jobs?repo=pine&revision=4bd9fac2a80e0aded6035e91b66b21242071cfdd)

**Comment by Mardak** [comment]
https://hg.mozilla.org/releases/mozilla-beta/rev/0922e331d03d

**Pull request merged**
