### PR TITLE
Bug 1421844 mochitests

### PR DESCRIPTION
**Pull request by piatra**

### CODE REVIEW

**Comment by piatra** [comment]
That change worked https://treeherder.mozilla.org/#/jobs?repo=try&revision=42f89b5fb71f055711dbd8275e9882a340652f8b

@Mardak  should I create a patch on m-c and request uplift? It's just tests so it should be easy (small patch).

**Comment by Mardak** [comment]
Why do we want to request uplift of this to beta? If anything, this has been a risky change twice breaking exports close to freeze date.

**Comment by piatra** [comment]
r? so I can merge to master again.

**Comment by Mardak** [comment]
> That change worked https://treeherder.mozilla.org/#/jobs?repo=try&revision=42f89b5fb71f055711dbd8275e9882a340652f8b

Where do you see the test that was failing on pine passing in that try link?

**Comment by piatra** [comment]
@Mardak not sure what how, previous try had win32,win64 I expected Windows 7 to be there.
Did another try push with [`-p all`](https://treeherder.mozilla.org/#/jobs?repo=try&revision=0720ba14775f35207fe53e7a79ceebb190d29e2e) and still not there. Is there something else for triggering those tests?

**Comment by Mardak** [comment]
Mysterious.. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1429947 for the win32 build failure.

I pushed to an older mozilla-central, and it seems to pass fine. https://treeherder.mozilla.org/#/jobs?repo=try&revision=d176372dd6161efc771872cc547a28c7506558d4

**Comment by as-pine-proxy** [comment]
[Treeherder: faa91d3c1b6934a2e8645def3ece0a36429384e8](https://treeherder.mozilla.org/#/jobs?repo=pine&revision=faa91d3c1b6934a2e8645def3ece0a36429384e8)

**Pull request merged**
