### PR TITLE
Fix(pingcentre): Collect region and profile creation date

### PR DESCRIPTION
**Pull request by ncloudioj**
This closes ping-centre [#117](https://github.com/mozilla/ping-centre/issues/117) and [#111](https://github.com/mozilla/ping-centre/issues/111)

### CODE REVIEW

**Comment by ncloudioj** [comment]
@fmarier r? data review, plz?

The UT is also looking to add the "region" (same as we're doing here) in the telemetry, see more details here https://bugzilla.mozilla.org/show_bug.cgi?id=1419788

**Comment by as-pine-proxy** [comment]
[Treeherder: 96feca4a424ee29c5b171d8f3c80e3b4fdfaec30](https://treeherder.mozilla.org/#/jobs?repo=pine&revision=96feca4a424ee29c5b171d8f3c80e3b4fdfaec30)

**Comment by fmarier** [comment]
Is there documentation about this to review?

**Comment by ncloudioj** [comment]
@fmarier Since those are not AS specific metrics, I didn't include them in the `data_events.md` and `data_dictionary.md`. Let me file a followup PR to add them in, hopefully that makes it easier to review.

**Pull request merged**
