### PR TITLE
(nobug) - Add mochitest for ReturnToAMO component

### PR DESCRIPTION
**Pull request by piatra**
~~Also a TC run that includes Windows: https://treeherder.mozilla.org/#/jobs?repo=try&revision=fa318b376d5e7bbcd77ec91fc94f037bd9dfa3b4~~

Finally got it green on windows https://treeherder.mozilla.org/#/jobs?repo=try&revision=7a6b54ee8dc82ee5b95952b9a6659addb6420033

TC is not relevant here only Win & OSX so we should notice any regressions when testing locally or exporting.

### CODE REVIEW

**Comment by rlr** [comment]
I am getting these errors when running locally against the latest m-c. Is there something special I need to do for the fluent changes maybe?

```
0:04.94 TEST_START: browser/components/newtab/test/browser/browser_onboarding_rtamo.js
 0:04.94 INFO Entering test bound setup
 0:04.94 INFO Leaving test bound setup
 0:04.94 INFO Entering test bound
 0:04.95 PASS Attribution data should be set - "addons.mozilla.org" == "addons.mozilla.org" -
 0:05.46 GECKO(23748) JavaScript error: , line 0: uncaught exception: [fluent][resolver] errors in en-US/newtab-section-header-pocket: ReferenceError: Unknown variable: provider.
 0:05.47 INFO Console message: [JavaScript Error: "uncaught exception: [fluent][resolver] errors in en-US/newtab-section-header-pocket: ReferenceError: Unknown variable: provider."]
 0:05.54 GECKO(23748) JavaScript error: , line 0: uncaught exception: [fluent][resolver] errors in en-US/newtab-section-header-pocket: ReferenceError: Unknown variable: provider.
 0:05.59 INFO Console message: [JavaScript Error: "uncaught exception: [fluent][resolver] errors in en-US/newtab-section-header-pocket: ReferenceError: Unknown variable: provider."]
 0:10.93 FAIL Uncaught exception - The modal setup should be completed - timed out after 50 tries.
 0:10.93 INFO Leaving test bound
 0:10.94 GECKO(23748) JavaScript error: resource://testing-common/PromiseTestUtils.jsm, line 110: uncaught exception: Object
 0:10.94 GECKO(23748) MEMORY STAT vsizeMaxContiguous not supported in this build configuration.
 0:10.94 GECKO(23748) MEMORY STAT | vsize 7109MB | residentFast 302MB | heapAllocated 137MB
 0:10.94 TEST_END: Test OK. Subtests passed 1/2. Unexpected 1
 0:10.94 FAIL Found an unexpected tab at the end of test run: about:welcome -
```

**Comment by piatra** [comment]
Not sure cc @JeaneC ?

**Comment by rlr** [comment]
I asked @Mardak and @JeaneC about those fluent-related console errors. They are "expected" for now but shouldn't have any effect on that test. So it passes for you locally? Even with`--verify`?

**Comment by Mardak** [comment]
Yup! @JeaneC has a fix to have a provider name set for our mochitests. PR should be incoming soon

**Comment by piatra** [comment]
@rlr updated with green try runs. `--verify` should work

https://treeherder.mozilla.org/#/jobs?repo=try&revision=aa0a06e88204ce88422fcc4da98dbe1349a184dc

**Comment by Mardak** [comment]
i rebased and fixed merge conflict in browser.ini

**Pull request merged**
