### PR TITLE
Bug 1548917 - [Accessibility] Focus state refinements

### PR DESCRIPTION
**Pull request by gvn**
QA:

- Set focus to a card
- Compare to [design spec](https://www.figma.com/file/0xZkmT86rSXbGRB4eIvrn0ts/New-Tab-Spec-for-Fx-v68?node-id=383%3A1)

### CODE REVIEW

**Comment by gvn** [comment]
Whoever has time to review...thx!

**Comment by gvn** [comment]
Fixed.

**Comment by punamdahiya** [comment]
@wolasi [spec here](https://www.figma.com/file/0xZkmT86rSXbGRB4eIvrn0ts/New-Tab-Spec-for-Fx-v68?node-id=383%3A0) says domain color as #005A71, is that for focus and active state?

**Comment by punamdahiya** [comment]
Sees below state (last story link stayed visited blue), if a user drags the link and change focus to another story. I believe its an edge case and should be ok.
blue text stayed after lose focus

**Comment by gvn** [comment]
Thanks! Design was approved as implemented, but follow-on tickets can certainly be filed if more changes are desired. 👍

**Comment by wolasi** [comment]
> @wolasi [spec here](https://www.figma.com/file/0xZkmT86rSXbGRB4eIvrn0ts/New-Tab-Spec-for-Fx-v68?node-id=383%3A0) says domain color as #005A71, is that for focus and active state?

@punamdahiya that was referencing the older domain color, this task predates another task in which domain color was changed to gray.

**Pull request merged**
