### PR TITLE
chore(mc): Port Bug 1440284 - change this.EXPORTED_SYMBOLS back to var EXPORTED_SYMBOLS in JS modules, r=mccr8.

### PR DESCRIPTION
**Pull request by Mardak**
Port https://hg.mozilla.org/mozilla-central/rev/b599a95ce057 and its merge conflict resolution https://hg.mozilla.org/mozilla-central/rev/683e5aafae7c

---
Old stuff:
Doesn't actually pass linting yet, but on top of #4001, it at least can run buildmc and testmc.

We should also additionally fix up the various `var … = class … {};` to just be `class … {}`

linting errors right now:
```
activity-stream/system-addon/common/Actions.jsm (12/0)
  ✖    6:1  Unexpected var, use let or const instead                                                                          no-var
  ✖    7:1  Unexpected var, use let or const instead                                                                          no-var
  ✖    8:1  Unexpected var, use let or const instead                                                                          no-var
  ✖    9:1  Unexpected var, use let or const instead                                                                          no-var
  ✖   10:1  Unexpected var, use let or const instead                                                                          no-var
  ✖  280:1  All 'var' declarations must be at the top of the function scope                                                   vars-on-top
  ✖  280:1  Unexpected var, use let or const instead                                                                          no-var
  ✖  296:1  All 'var' declarations must be at the top of the function scope                                                   vars-on-top
  ✖  296:1  Unexpected var, use let or const instead                                                                          no-var
  ✖  296:5  'actionUtils' is assigned a value but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars
  ✖  341:1  All 'var' declarations must be at the top of the function scope                                                   vars-on-top
  ✖  341:1  Unexpected var, use let or const instead                                                                          no-var

activity-stream/system-addon/common/Dedupe.jsm (3/0)
  ✖   1:1  Unexpected var, use let or const instead                                                                     no-var
  ✖   1:5  'Dedupe' is assigned a value but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars
  ✖  34:1  Unexpected var, use let or const instead                                                                     no-var

activity-stream/system-addon/common/PerfService.jsm (5/0)
  ✖  124:1  All 'var' declarations must be at the top of the function scope                                                   vars-on-top
  ✖  124:1  Unexpected var, use let or const instead                                                                          no-var
  ✖  124:5  'perfService' is assigned a value but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars
  ✖  125:1  All 'var' declarations must be at the top of the function scope                                                   vars-on-top
  ✖  125:1  Unexpected var, use let or const instead                                                                          no-var

activity-stream/system-addon/common/PrerenderData.jsm (5/0)
  ✖  49:1  All 'var' declarations must be at the top of the function scope                                                     vars-on-top
  ✖  49:1  Unexpected var, use let or const instead                                                                            no-var
  ✖  49:5  'PrerenderData' is assigned a value but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars
  ✖  99:1  All 'var' declarations must be at the top of the function scope                                                     vars-on-top
  ✖  99:1  Unexpected var, use let or const instead                                                                            no-var

activity-stream/system-addon/common/Reducers.jsm (6/0)
  ✖   58:10  'insertPinned' is defined but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/       no-unused-vars
  ✖  357:1   All 'var' declarations must be at the top of the function scope                                                vars-on-top
  ✖  357:1   Unexpected var, use let or const instead                                                                       no-var
  ✖  357:5   'reducers' is assigned a value but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars
  ✖  359:1   All 'var' declarations must be at the top of the function scope                                                vars-on-top
  ✖  359:1   Unexpected var, use let or const instead                                                                       no-var

activity-stream/system-addon/lib/ActivityStream.jsm (5/0)
  ✖  245:1  All 'var' declarations must be at the top of the function scope                                                      vars-on-top
  ✖  245:1  Unexpected var, use let or const instead                                                                             no-var
  ✖  245:5  'ActivityStream' is assigned a value but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars
  ✖  350:1  All 'var' declarations must be at the top of the function scope                                                      vars-on-top
  ✖  350:1  Unexpected var, use let or const instead                                                                             no-var

activity-stream/system-addon/lib/ActivityStreamMessageChannel.jsm (5/0)
  ✖   24:1  All 'var' declarations must be at the top of the function scope                                                                    vars-on-top
  ✖   24:1  Unexpected var, use let or const instead                                                                                           no-var
  ✖   24:5  'ActivityStreamMessageChannel' is assigned a value but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars
  ✖  259:1  All 'var' declarations must be at the top of the function scope                                                                    vars-on-top
  ✖  259:1  Unexpected var, use let or const instead                                                                                           no-var

activity-stream/system-addon/lib/ActivityStreamPrefs.jsm (8/0)
  ✖   12:1  All 'var' declarations must be at the top of the function scope                                                    vars-on-top
  ✖   12:1  Unexpected var, use let or const instead                                                                           no-var
  ✖   12:5  'Prefs' is assigned a value but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/         no-unused-vars
  ✖   42:1  All 'var' declarations must be at the top of the function scope                                                    vars-on-top
  ✖   42:1  Unexpected var, use let or const instead                                                                           no-var
  ✖   42:5  'DefaultPrefs' is assigned a value but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars
  ✖  106:1  All 'var' declarations must be at the top of the function scope                                                    vars-on-top
  ✖  106:1  Unexpected var, use let or const instead                                                                           no-var

activity-stream/system-addon/lib/FaviconFeed.jsm (5/0)
  ✖   24:1  All 'var' declarations must be at the top of the function scope                                                   vars-on-top
  ✖   24:1  Unexpected var, use let or const instead                                                                          no-var
  ✖   24:5  'FaviconFeed' is assigned a value but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars
  ✖  161:1  All 'var' declarations must be at the top of the function scope                                                   vars-on-top
  ✖  161:1  Unexpected var, use let or const instead                                                                          no-var

activity-stream/system-addon/lib/FilterAdult.jsm (3/0)
  ✖  38:10  'filterAdult' is defined but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars
  ✖  49:1   All 'var' declarations must be at the top of the function scope                                          vars-on-top
  ✖  49:1   Unexpected var, use let or const instead                                                                 no-var

activity-stream/system-addon/lib/HighlightsFeed.jsm (5/0)
  ✖   30:1  All 'var' declarations must be at the top of the function scope                                                      vars-on-top
  ✖   30:1  Unexpected var, use let or const instead                                                                             no-var
  ✖   30:5  'HighlightsFeed' is assigned a value but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars
  ✖  227:1  All 'var' declarations must be at the top of the function scope                                                      vars-on-top
  ✖  227:1  Unexpected var, use let or const instead                                                                             no-var

activity-stream/system-addon/lib/LinksCache.jsm (3/0)
  ✖   6:1  Unexpected var, use let or const instead                                                                         no-var
  ✖  21:1  Unexpected var, use let or const instead                                                                         no-var
  ✖  21:5  'LinksCache' is assigned a value but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars

activity-stream/system-addon/lib/ManualMigration.jsm (5/0)
  ✖  17:1  All 'var' declarations must be at the top of the function scope                                                       vars-on-top
  ✖  17:1  Unexpected var, use let or const instead                                                                              no-var
  ✖  17:5  'ManualMigration' is assigned a value but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars
  ✖  99:1  All 'var' declarations must be at the top of the function scope                                                       vars-on-top
  ✖  99:1  Unexpected var, use let or const instead                                                                              no-var

activity-stream/system-addon/lib/NewTabInit.jsm (3/0)
  ✖  12:1  Unexpected var, use let or const instead                                                                         no-var
  ✖  12:5  'NewTabInit' is assigned a value but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars
  ✖  52:1  Unexpected var, use let or const instead                                                                         no-var

activity-stream/system-addon/lib/PersistentCache.jsm (5/0)
  ✖  14:1  All 'var' declarations must be at the top of the function scope                                                       vars-on-top
  ✖  14:1  Unexpected var, use let or const instead                                                                              no-var
  ✖  14:5  'PersistentCache' is assigned a value but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars
  ✖  82:1  All 'var' declarations must be at the top of the function scope                                                       vars-on-top
  ✖  82:1  Unexpected var, use let or const instead                                                                              no-var

activity-stream/system-addon/lib/PlacesFeed.jsm (2/0)
  ✖  329:1  All 'var' declarations must be at the top of the function scope  vars-on-top
  ✖  329:1  Unexpected var, use let or const instead                         no-var

activity-stream/system-addon/lib/PrefsFeed.jsm (5/0)
  ✖  13:1  All 'var' declarations must be at the top of the function scope                                                 vars-on-top
  ✖  13:1  Unexpected var, use let or const instead                                                                        no-var
  ✖  13:5  'PrefsFeed' is assigned a value but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars
  ✖  96:1  All 'var' declarations must be at the top of the function scope                                                 vars-on-top
  ✖  96:1  Unexpected var, use let or const instead                                                                        no-var

activity-stream/system-addon/lib/Screenshots.jsm (4/0)
  ✖   6:1  Unexpected var, use let or const instead                                                                          no-var
  ✖  27:1  All 'var' declarations must be at the top of the function scope                                                   vars-on-top
  ✖  27:1  Unexpected var, use let or const instead                                                                          no-var
  ✖  27:5  'Screenshots' is assigned a value but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars

activity-stream/system-addon/lib/SectionsManager.jsm (2/0)
  ✖  351:1  All 'var' declarations must be at the top of the function scope  vars-on-top
  ✖  351:1  Unexpected var, use let or const instead                         no-var

activity-stream/system-addon/lib/ShortURL.jsm (4/0)
  ✖  35:1   More than 1 blank line not allowed                                                                    no-multiple-empty-lines
  ✖  45:10  'shortURL' is defined but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars
  ✖  71:1   All 'var' declarations must be at the top of the function scope                                       vars-on-top
  ✖  71:1   Unexpected var, use let or const instead                                                              no-var

activity-stream/system-addon/lib/SnippetsFeed.jsm (5/0)
  ✖   32:1  All 'var' declarations must be at the top of the function scope                                                    vars-on-top
  ✖   32:1  Unexpected var, use let or const instead                                                                           no-var
  ✖   32:5  'SnippetsFeed' is assigned a value but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars
  ✖  151:1  All 'var' declarations must be at the top of the function scope                                                    vars-on-top
  ✖  151:1  Unexpected var, use let or const instead                                                                           no-var

activity-stream/system-addon/lib/Store.jsm (3/0)
  ✖   18:1  Unexpected var, use let or const instead                                                                    no-var
  ✖   18:5  'Store' is assigned a value but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars
  ✖  160:1  Unexpected var, use let or const instead                                                                    no-var

activity-stream/system-addon/lib/SystemTickFeed.jsm (5/0)
  ✖  16:1  All 'var' declarations must be at the top of the function scope                                                      vars-on-top
  ✖  16:1  Unexpected var, use let or const instead                                                                             no-var
  ✖  16:5  'SystemTickFeed' is assigned a value but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars
  ✖  34:1  All 'var' declarations must be at the top of the function scope                                                      vars-on-top
  ✖  34:1  Unexpected var, use let or const instead                                                                             no-var

activity-stream/system-addon/lib/TelemetryFeed.jsm (5/0)
  ✖   42:1  All 'var' declarations must be at the top of the function scope                                                     vars-on-top
  ✖   42:1  Unexpected var, use let or const instead                                                                            no-var
  ✖   42:5  'TelemetryFeed' is assigned a value but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars
  ✖  475:1  All 'var' declarations must be at the top of the function scope                                                     vars-on-top
  ✖  475:1  Unexpected var, use let or const instead                                                                            no-var

activity-stream/system-addon/lib/TippyTopProvider.jsm (5/0)
  ✖  21:1  All 'var' declarations must be at the top of the function scope                                                        vars-on-top
  ✖  21:1  Unexpected var, use let or const instead                                                                               no-var
  ✖  21:5  'TippyTopProvider' is assigned a value but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars
  ✖  53:1  All 'var' declarations must be at the top of the function scope                                                        vars-on-top
  ✖  53:1  Unexpected var, use let or const instead                                                                               no-var

activity-stream/system-addon/lib/TopSitesFeed.jsm (5/0)
  ✖   32:1  All 'var' declarations must be at the top of the function scope                                                    vars-on-top
  ✖   32:1  Unexpected var, use let or const instead                                                                           no-var
  ✖   32:5  'TopSitesFeed' is assigned a value but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars
  ✖  350:1  All 'var' declarations must be at the top of the function scope                                                    vars-on-top
  ✖  350:1  Unexpected var, use let or const instead                                                                           no-var

activity-stream/system-addon/lib/TopStoriesFeed.jsm (5/0)
  ✖   30:1  All 'var' declarations must be at the top of the function scope                                                      vars-on-top
  ✖   30:1  Unexpected var, use let or const instead                                                                             no-var
  ✖   30:5  'TopStoriesFeed' is assigned a value but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars
  ✖  509:1  All 'var' declarations must be at the top of the function scope                                                      vars-on-top
  ✖  509:1  Unexpected var, use let or const instead                                                                             no-var

activity-stream/system-addon/lib/UserDomainAffinityProvider.jsm (5/0)
  ✖   75:1  All 'var' declarations must be at the top of the function scope                                                                  vars-on-top
  ✖   75:1  Unexpected var, use let or const instead                                                                                         no-var
  ✖   75:5  'UserDomainAffinityProvider' is assigned a value but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars
  ✖  329:1  All 'var' declarations must be at the top of the function scope                                                                  vars-on-top
  ✖  329:1  Unexpected var, use let or const instead                                                                                         no-var

activity-stream/system-addon/lib/UTEventReporting.jsm (5/0)
  ✖  16:1  All 'var' declarations must be at the top of the function scope                                                        vars-on-top
  ✖  16:1  Unexpected var, use let or const instead                                                                               no-var
  ✖  16:5  'UTEventReporting' is assigned a value but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars
  ✖  59:1  All 'var' declarations must be at the top of the function scope                                                        vars-on-top
  ✖  59:1  Unexpected var, use let or const instead                                                                               no-var

✖ 138 errors
```

### CODE REVIEW

**Comment by Mardak** [comment]
@Standard8 any suggestions on how to debug the `no-unused-vars`? It seems to error in activity stream, but not in mozilla-central (even when removing the "browser/extensions/**/*.jsm" override for `"vars": "local"`…
`  ✖  296:5  'actionUtils' is assigned a value but never used. Allowed unused vars must match /^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS/  no-unused-vars`

If I `--print-config`, I do see:
```
./node_modules/.bin/eslint --print-config system-addon/common/Actions.jsm
{
  …,
  "env": {
    "browser": false,
    "es6": true,
    "node": true,
    "mozilla/jsm": true
  },
  "rules": {
    …
    "no-unused-vars": [
      "error",
      {
        "args": "none",
        "vars": "all",
        "varsIgnorePattern": "^Cc|Ci|Cu|Cr|EXPORTED_SYMBOLS"
      }
    ],
    "mozilla/mark-exported-symbols-as-used": "error"
  },
  "parserOptions": {
    "ecmaVersion": 9,
    "ecmaFeatures": {
      "globalReturn": true,
      "jsx": true
    },
    "sourceType": "module"
  },
  "plugins": [
    "mozilla",
    "no-unsanitized",
    "import",
    "json",
    "promise",
    "react"
  ],
  "extends": [
    "eslint:recommended",
    "plugin:mozilla/recommended"
  ],
  "files": "**/*.jsm"
}
```

And if I modify `mark-exported-symbols-as-used.js` https://searchfox.org/mozilla-central/source/tools/lint/eslint/eslint-plugin-mozilla/lib/rules/mark-exported-symbols-as-used.js#53
```js
    VariableDeclaration(node, parents) {
      for (let item of node.declarations) {
        console.log(item && item.id && item.id.name, isGlobalScope());
      }
```
```
MAIN_MESSAGE_TYPE false
CONTENT_MESSAGE_TYPE false
PRELOAD_MESSAGE_TYPE false
UI_CODE false
BACKGROUND_PROCESS false
globalImportContext false
actionTypes false
type false
meta false
action false
action false
action false
action false
action false
actionCreators false
actionUtils false
EXPORTED_SYMBOLS false
```
So it looks like the top-level `var EXPORTED_SYMBOLS = [` isn't `isGlobalScope()`, although I don't quite understand `context.getScope().upper`… perhaps being set in a different way by other plugins? ?

**Comment by Standard8** [comment]
@Mardak I went through your config disabling a few things. The `.eslintrc.js` is defining `"sourceType": "module"` which means it is trying to treat all files as ECMAScript modules. That's different to m-c where we use the default of script.

When I turn that off, the global scope is correctly set, although [no-implicit-vars](https://eslint.org/docs/rules/no-implicit-globals) then starts failing, but reading the reasoning for that rule, I don't think you want that on for jsm files anyway.

**Comment by Mardak** [comment]
Aha! Thanks for figuring that out. I ended up adding an override for **jsm stuff turning off node, sourceType, and no-implicit-vars, and things look good. :)

**Comment by Mardak** [comment]
r?@k88hudson The first commit adds the eslint overrides for **jsm and I patched the m-c patch and ran `eslint --fix`. The patching of the patch was to use `const` instead of `var` and removing the extra variable declaration for `class`.

The second commit has additional removal of "^this." lines.

**Comment by k88hudson** [comment]
I looks like there is no problem with `var EXPORTED_SYMBOLS = ["foo"]` but changing `this.foo = foo` to just `const foo` is resulting in `foo` being undefined 😭

**Comment by fqueze** [comment]
"changing this.foo = foo to just const foo is resulting in foo being undefined"
My script changed "this.foo =" to "var foo =" rather than "const foo =" and that avoids the problem.

**Comment by k88hudson** [comment]
@fqueze is it possible that this doesn't work with `class`es? i.e. `var Foo = class Foo{}`? I'm still seeing problems with importing it

**Comment by Mardak** [comment]
Turns out the problem is that `const`/`let`/`class` at the top level define things on the *global scope* whereas `var`/`this.`/`function` (declaration) adds it to the global object.

`EXPORTED_SYMBOLS` itself apparently can just be in the global scope and not necessarily on the global object to export things.

**Comment by Mardak** [comment]
After more discussion on irc, sounds like to keep `EXPORTED_SYMBOLS` exporting the right stuff from the global object, we would rather use `this.Foo` instead of `var Foo`. So in porting the changes, we'll revert the `var Foo` changes except for the function declarations, and make it `const EXPORTED_SYMBOLS`

**Comment by Mardak** [comment]
@Standard8 from the previous comment, it looks like not allowing `let` (which theoretically should have not allowed `const` either) is no longer applicable??
```
34:1  error  EXPORTED_SYMBOLS cannot be declared via `let`. Use `var` or `this.EXPORTED_SYMBOLS =`  mozilla/mark-exported-symbols-as-used (eslint)
```

Maybe something got changed in the switch to `ChromeUtils.import` ?

**Comment by Mardak** [comment]
@k88hudson I updated the commit fixing up our eslintrc and porting only the `this.EXPORTED_SYMBOLS` switch (to `const`) and the removal of `this.func = function func()` as a plain `function func()` would declare it on the global object anyway.

**Comment by Mardak** [comment]
I don't quite understand the difference between how "EXPORTED_SYMBOLS" name is checked vs how the actually exported symbol ids are checked:
https://searchfox.org/mozilla-central/source/js/xpconnect/loader/mozJSComponentLoader.cpp#1149-1195

But it would at a glance seem to get things pretty similarly, so odd why EXPORTED_SYMBOLS can be const at the global scope and seemingly works but the actually exported things need to be on the global object…

**Comment by Standard8** [comment]
@Mardak: `let` in the global scope is wrong, and may not be supported for too long - I had a chat with one of the #jsapi folks about this and although let 'works' at the moment, that is likely to be changed/corrected, and hence they requested that change.

The reason is that once the file is processed, any `let`s in the global scope will go out of scope.

We didn't discuss `const` at the time.

**Comment by Mardak** [comment]
I would think `const` would be treated similarly as `let` as it adds the variable to the scope but not the global object. So I guess if we don't want to use `var`, we should just keep/revert the `this.EXPORTED_SYMBOLS =`?

**Comment by Standard8** [comment]
I think tcampbell might be the right person to ask here. He's the one that said to me that `var EXPORTED_SYMBOLS` is the preferred way.

**Comment by Mardak** [comment]
Given that there's interest in making jsm more like esmodules with no global object and `export` statements instead of `EXPORTED_SYMBOLS`, we'll need to change almost all the lines touched here anyway. We'll merge this PR, so we can resume exporting to m-c again.

**Comment by as-pine-proxy** [comment]
[Treeherder: f9918d91190800ea7645fdedcfa13de55915bac6](https://treeherder.mozilla.org/#/jobs?repo=pine&revision=f9918d91190800ea7645fdedcfa13de55915bac6)

**Pull request merged**
