### PR TITLE
[fix snippets-service #862] Add SubmitForm error button label.

### PR DESCRIPTION
**Pull request by jpetto**
Fixes mozmeao/snippets-service#862

Related bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1510331

### CODE REVIEW

**Comment by jpetto** [comment]
@piatra Added the corresponding key/value to the `NEWSLETTER_TEST_DEFAULTS` test snippet. However, I'm not sure how to force an error on submission, so I wasn't able to manually verify the `error_button_label` is showing (though the tests should be handling this).

Is there a way to force a form submit failure on a test snippet?

**Comment by piatra** [comment]
@jpetto sorry there's no easy way to do it because the URLs are hardcoded. To test I made the snippet show and then using the browser devtools edit the `form url`. This would force it to fail.

**Comment by piatra** [comment]
lgtm 

image

**Pull request merged**
