### PR TITLE
Add karma-sinon and karma-chai

### PR DESCRIPTION
**Pull request by k88hudson**
This patch adds `karma-sinon` and `karma-chai`, which allows us to use `sinon` and `chai` globally instead of requiring them each time. Part of work done in #1082.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-stream/1102)

### CODE REVIEW

**Comment by k88hudson** [comment]
@rlr R?

**Comment by rlr** [comment]
Looks good. Is that travis failure unrelated? I'm restarting it in case it was one of the intermittent fails.

```
TabTracker.test_TabTracker_close_window_with_multitabs'

console.info: activity-streams: pass: tabData starts out empty

console.info: activity-streams: -3-31 0 TAB_OPEN 

console.info: activity-streams: -3-31 0 TAB_OPEN 

console.log: activity-streams: [JavaScript Warning: "Content Security Policy: Directive 'frame-src' has been deprecated. Please use directive 'child-src' instead."]

console.log: activity-streams: [JavaScript Warning: "Content Security Policy: Directive 'frame-src' has been deprecated. Please use directive 'child-src' instead."]

console.info: activity-streams: -3-31 168 WORKER_ATTACHED 

console.info: activity-streams: -3-32 0 TAB_OPEN 

console.info: activity-streams: -3-32 0 TAB_OPEN 

console.log: activity-streams: TELEMETRY PING: {"session_id":"{c4e29bb7-5216-47b0-9005-3dc82a7da271}","total_history_size":0,"total_bookmarks":0,"client_id":"50099a81-204e-41af-b8f8-d929b484ebf9","addon_version":"1.1.1","locale":"en-US","page":"NEW_TAB","experiment_id":"foo_01","action":"activity_stream_session","unload_reason":"unfocus","url":"resource://activity-streams/data/content/activity-streams.html#/","tab_id":"-3-31","load_reason":"none","session_duration":0}

JPM [error] JavaScript warning: resource://activity-streams/data/content/bundle.js, line 67468: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

console.log: activity-streams: [JavaScript Warning: "mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create" {file: "resource://activity-streams/data/content/bundle.js" line: 67468}]

console.info: activity-streams: -3-32 330 WORKER_ATTACHED 

console.log: activity-streams: [JavaScript Warning: "Content Security Policy: Directive 'frame-src' has been deprecated. Please use directive 'child-src' instead."]

console.log: activity-streams: [JavaScript Warning: "Content Security Policy: Directive 'frame-src' has been deprecated. Please use directive 'child-src' instead."]

console.info: activity-streams: -3-31 1455 TOP_FRECENT_SITES_REQUEST 

console.info: activity-streams: -3-31 1461 RECENT_LINKS_REQUEST 

console.info: activity-streams: -3-31 1469 HIGHLIGHTS_LINKS_REQUEST 

console.info: activity-streams: -3-31 1485 RECENT_BOOKMARKS_REQUEST 

console.info: activity-streams: -3-31 1489 SEARCH_STATE_REQUEST 

console.info: activity-streams: -3-31 1506 NOTIFY_PERFORMANCE:BASE_MOUNTED 

console.info: activity-streams: -3-31 1512 TAB_READY 

console.info: activity-streams: -3-31 1516 NOTIFY_PERFORMANCE:DOC_READY_STATE=interactive 

console.info: activity-streams: -3-31 1526 SEARCH_STATE_RESPONSE 37

console.info: activity-streams: -3-31 1531 TOP_FRECENT_SITES_RESPONSE 76

console.info: activity-streams: -3-31 1534 RECENT_LINKS_RESPONSE 73

console.info: activity-streams: -3-31 1537 HIGHLIGHTS_LINKS_RESPONSE 68

console.info: activity-streams: -3-31 1540 RECENT_BOOKMARKS_RESPONSE 55

JPM [error] JavaScript warning: resource://activity-streams/data/content/bundle.js, line 67468: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

console.log: activity-streams: [JavaScript Warning: "mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create" {file: "resource://activity-streams/data/content/bundle.js" line: 67468}]

console.info: activity-streams: -3-32 935 TOP_FRECENT_SITES_REQUEST 

console.info: activity-streams: -3-32 942 TOP_FRECENT_SITES_RESPONSE 7

console.info: activity-streams: -3-32 945 RECENT_LINKS_REQUEST 

console.info: activity-streams: -3-32 950 RECENT_LINKS_RESPONSE 5

console.info: activity-streams: -3-32 955 HIGHLIGHTS_LINKS_REQUEST 

console.info: activity-streams: -3-32 960 HIGHLIGHTS_LINKS_RESPONSE 5

console.info: activity-streams: -3-32 968 RECENT_BOOKMARKS_REQUEST 

console.info: activity-streams: -3-32 973 RECENT_BOOKMARKS_RESPONSE 5

console.info: activity-streams: -3-32 976 SEARCH_STATE_REQUEST 

console.info: activity-streams: -3-32 982 SEARCH_STATE_RESPONSE 6

console.info: activity-streams: -3-32 998 NOTIFY_PERFORMANCE:BASE_MOUNTED 

console.info: activity-streams: -3-32 1003 TAB_READY 

console.log: activity-streams: TELEMETRY PING: {"total_history_size":0,"total_bookmarks":0,"load_reason":"newtab","session_id":"{d580b4a3-8f8b-4fa4-98ab-44c4b2df12ab}","url":"resource://activity-streams/data/content/activity-streams.html#/","tab_id":"-3-32","client_id":"50099a81-204e-41af-b8f8-d929b484ebf9","addon_version":"1.1.1","locale":"en-US","page":"NEW_TAB","experiment_id":"foo_01","action":"activity_stream_session","unload_reason":"close","session_duration":13}

console.info: activity-streams: pass: The activity streams page was activated 2 times

console.error: activity-streams: 

  fail:

  Loaded for the expected reason - "none" == "newtab"

console.trace: activity-streams: 

_ecated/unit-test.js 108 fail

_/sdk/test/assert.js 88 fail

_/sdk/test/assert.js 123 equal

_/test-TabTracker.js 41 checkLoadUnloadReasons/<

_/test-TabTracker.js 40 checkLoadUnloadReasons

_/test-TabTracker.js 341 exports.test_TabTracker_close_window_with_multitabs

_re/modules/Task.jsm 315 TaskImpl_run
```

**Comment by k88hudson** [comment]
@rlr yes, looks like it was unrelated: are we all good?

**Comment by rlr** [comment]
yep, sorry. meant to add R+!

**Pull request merged**
