### PR TITLE
Preparing the release of Activity Stream 1.1.7

### PR DESCRIPTION
**Pull request by ncloudioj**
Hi all,

We are now preparing the release of A-S 1.1.7. The add-on has been made available at [pre-release channel](https://moz-activity-streams-prerelease.s3.amazonaws.com/dist/latest.html). Since this release also bases the "Activity Stream Variant" in the shield study, it only adds a few UI enhancements as well as various bugfixes on top of A-S 1.1.6.

# Highlights (Changelog)
* [new] Added a more informative page to replace the "Hang tight" spinner
* [fix] Fixed the SQL binding overflow issue in the metadata store
* [fix] Fixed the exception error message template in the metadata store
* [fix] Fixed the bug that made the context menu not clickable

# Release checklist
- QA
  - [x] @pdehaan 
  - [x] @SoftVision
- Product
  - [x] @nchapman 
  - [x] @aaronrbenson 
- Engineering
  - [x] @tspurway 
  - [x] @jennchaulk 

Please use the `release/block` or `release/uplift` to label the bug report as well as other release related issues. Once you finish the review, please check off the corresponding item in the above checklist.

Thanks

### CODE REVIEW

**Comment by pdehaan** [comment]
Needs rebase

**Comment by ncloudioj** [comment]
@pdehaan Please ignore those conflicts. We won't merge this PR back to master, instead we just use this PR to track the release process.

**Comment by k88hudson** [comment]
just a note that @tspurway is on PTO until next week, if that matters

**Comment by ncloudioj** [comment]
@k88hudson we can still bug him, can't we?

Heh, just kidding :)

**Comment by SoftVision-CiprianMuresan** [comment]
In our opinion, #1763 should be fixed before the 1.1.7 release as it is a regression.

**Comment by ncloudioj** [comment]
@SoftVision-CiprianMuresan Hey, so the patch to fix #1763 has been merged to this release. Could you verify it please?

Thanks for the feedback!

**Comment by Softvision-VladBacia** [comment]
The issue is no longer reproducible on the latest Activity Stream RC build v1.1.7-pre-release1479402489

**Comment by Softvision-VladBacia** [comment]
reminder for #1544  :)

**Comment by ncloudioj** [comment]
@Softvision-VladBacia Thanks for the reminder!

Yes, we had discussed about #1544 in the triage meeting yesterday. I think @nchapman is already on it and will make the change for Test Pilot soon.

**Comment by pdehaan** [comment]
Do we want to uplift the Webpack optimizations from #1814?

**Comment by ncloudioj** [comment]
@pdehaan Yup, definitely, easy win. Uplifting it right now.

**Comment by ncloudioj** [comment]
@jennchaulk Thanks Jenn!

**Comment by ncloudioj** [comment]
@pdehaan Uplifted! Looks good to me. Wanna take a quick look?

And the xpi size is downed by 25% 👍

**Comment by ncloudioj** [comment]
Close this as A-S 1.1.7 is out.

Thank you very much, everyone!

**Pull request closed without merging**
