### PR TITLE
Add table of contents, clarification for docs

### PR DESCRIPTION
**Pull request by k88hudson**
This patch cleans up our getting started page a little and adds a table of contents.

### CODE REVIEW

**Comment by k88hudson** [comment]
@piatra if you have any suggestions for things that might be helpful/are missing that would be super helpful as well

**Comment by piatra** [comment]
👍

**Comment by k88hudson** [comment]
Thanks!

**Comment by as-pine-proxy** [comment]
[Treeherder: f378724cb19a495398b4bec5ebfa6b09ea0c73e7](https://treeherder.mozilla.org/#/jobs?repo=pine&revision=f378724cb19a495398b4bec5ebfa6b09ea0c73e7)

**Pull request merged**
