### PR TITLE
fix(testpilot): #3112 - Self destruct

### LINKED ISSUE #3112: Migrate test pilot users to system-addon
We need to update test pilot add-on to have it uninstall itself unconditionally for all firefox versions.

At the same time we can just flip the `browser.newtabpage.activity-stream.enabled` to true.

Sounds like messaging has already been told to Test Pilot users that it has been graduated, so we can just do stuff.

### PR DESCRIPTION
**Pull request by ncloudioj**
This closes #3112.

### CODE REVIEW

**Comment by k88hudson** [comment]
Hey this looks good, any reason why we don't want to push the button on this?

**Comment by ncloudioj** [comment]
@k88hudson Yes, we could.

We still have 6000 daily active users on Test Pilot (mostly on 54&55). @tspurway will confirm it with Test Pilot team first, then we'll take action.

**Comment by as-pine-proxy** [comment]
[Treeherder: 3104a52863bfa3440cce9f48a216b167b1aab78e](https://treeherder.mozilla.org/#/jobs?repo=pine&revision=3104a52863bfa3440cce9f48a216b167b1aab78e)

**Pull request merged**
