### PR TITLE
fix vertical text cropping in items (#1526)

### LINKED ISSUE #1526: Description text is cut off on some highlight cards
On some of the highlight cards, the description text is not properly truncated or is overflowing it's container making the text cut off. Examples attached:

screen shot 2016-10-11 at 12 53 29 pm
screen shot 2016-10-11 at 12 57 56 pm

### PR DESCRIPTION
**Pull request by dmose**
fix(Highlights): fix vertical text cropping & layout in individual items (closes #1526)

The easiest way to test is to do:

npm run bundle
npm run storybook
(browse to localhost:9001)

and look over the various Highlight Item stories

### CODE REVIEW

**Comment by dmose** [comment]
@rlr, can you review these changes?

**Comment by rlr** [comment]
I fired up storybook for the first time (so cool! 👍 ) and I am still seeing some weird cropping:

screen shot 2016-10-20 at 2 43 09 pm

screen shot 2016-10-20 at 2 43 35 pm

screen shot 2016-10-20 at 2 43 42 pm

screen shot 2016-10-20 at 2 43 50 pm

**Comment by dmose** [comment]
@rlr, I can't reproduce this behavior.  My current suspicion is that this is a build problem.  Let's see if this fixes things:

* kill all your running "npm run ..." node processes for this repo
* ```# npm run clean```
* ```# npm run start```
** wait for the build to complete (eg you see a line starting with ```✓ Clean```)
* open another shell, and in that shell, execute:
** ```npm run storybook```
** wait for the build to complete (eg you see a line starting with ```webpack built```)
* navigate to http://localhost:9001/

If this fixes the problem, I think I know what's going on, and I'll file a separate issue to fix that.

If it doesn't fix the problem, it'll be very interesting for you to try ```npm run firefox``` in another shell and let me know whether you can see the problem in the real live new tab page...

**Comment by rlr** [comment]
Those steps fixed the problem for me 👍

**Pull request merged**
