### PR TITLE
chore(mc): Port Bug 1432992 - Remove definitions of Ci, Cr, Cc, and Cu

### PR DESCRIPTION
**Pull request by Mardak**
Things applied cleanly again :)
`activity-stream/system-addon$ git -C ../../mozilla-central sh a9a499cb3f84e69bbcb1bdbc84ffbfad8807c728 browser/extensions/activity-stream | patch -p4`

@Standard8 `eslint-plugin-mozilla` needs to be bumped to include https://hg.mozilla.org/mozilla-central/rev/e51fa5f76367 from https://bugzilla.mozilla.org/show_bug.cgi?id=767640

(There's an unrelated change that we'll need to fix when updating our dependency)
```
activity-stream/bin/render-activity-stream-html.js (1/0)
  ✖  153:10  use .includes instead of .indexOf  mozilla/use-includes-instead-of-indexOf
```

### CODE REVIEW

**Comment by Standard8** [comment]
@Mardak, uh sorry I thought that had already been published. I'm working on an update with some new rules in [bug 1230369](https://bugzilla.mozilla.org/show_bug.cgi?id=1230369)

**Comment by Standard8** [comment]
@Mardak I finally managed to publish 0.8.1.

**Comment by Mardak** [comment]
Thanks! Things look good locally for me. Turns out porting this was trickier than I thought too ;)

**Comment by as-pine-proxy** [comment]
[Treeherder: 4799beb41f333120aa40d1177681822c3929f392](https://treeherder.mozilla.org/#/jobs?repo=pine&revision=4799beb41f333120aa40d1177681822c3929f392)

**Pull request merged**
