### PR TITLE
fix (experiments): turn off screenshots experiment

### PR DESCRIPTION
**Pull request by rlr**
r? @sarracini

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-stream/2103)

### CODE REVIEW

**Comment by rlr** [comment]
@sarracini yep, I did that first but then notice that the thing disappears from `about:config` which kind of sucks because then nobody will be able to enable it for testing.

**Comment by rlr** [comment]
Or maybe do that but only in the release branch?

**Comment by sarracini** [comment]
@rlr i wonder if maybe you commit this directly to the release branch instead of master? and that way we can keep it on on master?

**Comment by rlr** [comment]
ok. let me redo this against release branch 👍

**Pull request closed without merging**
