### PR TITLE
fix (addon) Remove timeline toolbar button

### LINKED ISSUE #1466: Remove Timeline Button
In order to remove the button from the menu bar in Firefox, we should remove the following from `ActivityStream.js`:

- the `_setupButton` function
- any references to `._button`

### PR DESCRIPTION
**Pull request by rlr**
Fixes #1466

### CODE REVIEW

**Comment by k88hudson** [comment]
Can you add a second commit to this to remove `/timeline` and `/timeline/bookmarks` from `getAppURLs` actually? Since you are here anyway

**Comment by rlr** [comment]
oh good point!

**Comment by rlr** [comment]
@k88hudson should we remove the `RECENT_BOOKMARKS_REQUEST` and `RECENT_BOOKMARKS_RESPONSE` actions and related code too?

**Comment by k88hudson** [comment]
@rlr there is actually a separate ticket for that

**Pull request merged**
