### PR TITLE
Bug 1581570 - Spocs placement bug impacting non placements fixed

### PR DESCRIPTION
**Pull request by ScottDowne**
Steps to test in bugzilla

### CODE REVIEW

**Comment by ScottDowne** [comment]
So right now we have this concept of "if no placements assume spocs as the only placement"

It was the cause of this bug because I implemented the fallback in the usage of placements inside DS Feed and not actually defaulting the placements inside the reducer.

This can be moved into the reducer's `DISCOVERY_STREAM_SPOCS_PLACEMENTS` in the future, but I hesitated to do that because doing it the way I have it in the patch is easier to uplift because it impacts less.

**Comment by gvn** [comment]
Failing Taskcluster

**Comment by gvn** [comment]
When I follow STR I get a new spoc where the old one was dismissed after I refresh. Is that expected?

**Comment by ScottDowne** [comment]
Yeah, that's expected. If you refresh after dismiss, it does a fresh load including spoc placement.

We only keep the spoc out of that spot for that specific tab instance.

**Comment by ScottDowne** [comment]
@gvn should be ready for another look.

**Pull request merged**
