### PR TITLE
fix(content): Fixes #986 Recommendations link to shortened pocket url

### LINKED ISSUE #986: Recommended items should link to the Pocket short url for that item
Pocket's API returns a short link so that they are able to track click-through rates. It appears as though we're linking directly to the webpages.

### PR DESCRIPTION
**Pull request by sarracini**
@jaredkerim r? 🐱

Fixes #986 

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-stream/1069)

### CODE REVIEW

**Comment by edmoz** [comment]
Oh hai - can we wait on merging this because we're waiting on legal to update our privacy notice.

**Comment by jaredkerim** [comment]
r+ pending legal review

**Comment by k88hudson** [comment]
@sarracini what's the status on this?

**Comment by sarracini** [comment]
forever blocked on legal

**Pull request closed without merging**
