### PR TITLE
chore(experiment): #931 Disable experiment for context menu

### PR DESCRIPTION
**Pull request by ncloudioj**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-stream/932)

### CODE REVIEW

**Comment by ncloudioj** [comment]
@k88hudson r?

**Comment by k88hudson** [comment]
@ncloudioj is this intended to be a permanent disable or temporary? If it's permanent should we maybe remove the relevant code block and test as well?

**Comment by ncloudioj** [comment]
I'm not sure whether or not we will do similar exps on the context menu. But for this one, we want to permanently remove it, so I think I'll take it out from the code base.

**Comment by k88hudson** [comment]
Ok, thanks!

**Comment by ncloudioj** [comment]
@k88hudson One more round?

**Comment by k88hudson** [comment]
Looks good, just needs a rebase

**Pull request merged**
