### PR TITLE
fix (addon): #1024 fix package script

### LINKED ISSUE #1024: Cannot build the Activity Stream xpi file
We have followed the steps from [Installation](https://github.com/mozilla/activity-stream#installation) section and all went ok. After that we've run the `npm run package` command in Ubuntu 14.04 and the following error was displayed:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'package' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose run-script [ 'prepackage', 'package', 'postpackage' ]
5 info lifecycle activity-streams@1.1.1~prepackage: activity-streams@1.1.1
6 silly lifecycle activity-streams@1.1.1~prepackage: no script for prepackage, continuing
7 info lifecycle activity-streams@1.1.1~package: activity-streams@1.1.1
8 verbose lifecycle activity-streams@1.1.1~package: unsafe-perm in lifecycle true
9 verbose lifecycle activity-streams@1.1.1~package: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/vladbacia/activity-stream/node_modules/.bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle activity-streams@1.1.1~package: CWD: /home/vladbacia/activity-stream
11 silly lifecycle activity-streams@1.1.1~package: Args: [ '-c',
11 silly lifecycle   'npm run bundle && jpm xpi && mv @activity-streams-$npm_package_version.xpi dist/activity-streams-$npm_package_version.xpi' ]
12 silly lifecycle activity-streams@1.1.1~package: Returned: code: 1  signal: null
13 info lifecycle activity-streams@1.1.1~package: Failed to exec package script
14 verbose stack Error: activity-streams@1.1.1 package: `npm run bundle && jpm xpi && mv @activity-streams-$npm_package_version.xpi dist/activity-streams-$npm_package_version.xpi`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid activity-streams@1.1.1
16 verbose cwd /home/vladbacia/activity-stream
17 error Linux 3.19.0-65-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "package"
19 error node v6.3.1
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error activity-streams@1.1.1 package: `npm run bundle && jpm xpi && mv @activity-streams-$npm_package_version.xpi dist/activity-streams-$npm_package_version.xpi`
22 error Exit status 1
23 error Failed at the activity-streams@1.1.1 package script 'npm run bundle && jpm xpi && mv @activity-streams-$npm_package_version.xpi dist/activity-streams-$npm_package_version.xpi'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the activity-streams package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run bundle && jpm xpi && mv @activity-streams-$npm_package_version.xpi dist/activity-streams-$npm_package_version.xpi
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs activity-streams
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls activity-streams
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

### PR DESCRIPTION
**Pull request by rlr**
Fixes #1024 

@SoftVision-VladBacia are you able to try this out? Fixes it for me, but my error message was slightly different than yours on OS-X.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-stream/1030)

### CODE REVIEW

**Comment by pdehaan** [comment]
Doh, yeah, I think newer patch-level versions of JPM removed the leading "@" and version number from the generated XPI.

It also looks like Travis-CI is blowing up on "./test/test-ActivityStreams-private-browsing.test activity stream doesn't load in private windows":

```
1230 of 1231 tests passed.
There were test failures...
The following tests failed:
  ./test/test-ActivityStreams-private-browsing.test activity stream doesn't load in private windows: failure
```

See https://travis-ci.org/mozilla/activity-stream/builds/149616735#L785

```
console.info: activity-streams: executing './test/test-ActivityStreams-private-browsing.test activity stream doesn't load in private windows'
JPM [error] *************************
A coding exception was thrown and uncaught in a Task.
Full message: TypeError: tabs.activeTab is undefined
Full stack: handlePerformanceEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/TabTracker.js:120:5
RecommendationProvider.prototype.asyncSetRecommendedContent<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/RecommendationProvider.js:85:7
TaskImpl_run@resource://gre/modules/Task.jsm:315:40
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:933:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:812:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:746:11
*************************
console.log: activity-streams: [JavaScript Error: "tabs.activeTab is undefined" {file: "resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/TabTracker.js" line: 120}]
console.info: activity-streams: pass: undefined
console.error: activity-streams: 
  fail:
  There was an uncaught Promise rejection: TypeError: tabs.activeTab is undefined @ resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/TabTracker.js:120
handlePerformanceEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/TabTracker.js:120:5
RecommendationProvider.prototype.asyncSetRecommendedContent<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/RecommendationProvider.js:85:7
TaskImpl_run@resource://gre/modules/Task.jsm:315:40
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:933:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:812:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:746:11
console.trace: activity-streams: 
_ecated/unit-test.js 108 fail
```

**Comment by rlr** [comment]
Gah! Yeah, that's an intermittent error - issue #1001 ... I restarted travis.

**Comment by pdehaan** [comment]
Also, looking through the 3000+ line Travis-CI logs, not sure why we have about 65 results that say:

```
console.info: activity-streams: pass: undefined
```

I don't know where the `undefined` is coming from, if we have some unnamed tests or just something else weird.

**Comment by rlr** [comment]
once pull #1031 lands, this should stop failing 😡

**Comment by dmose** [comment]
Works nicely and looks good to me.  r=dmose

**Comment by dmose** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/activity-stream/1030)*

**Pull request merged**
