### PR TITLE
Fix Bug 1445157 - Move isCollapsed pref to IndexedDB

### PR DESCRIPTION
**Pull request by piatra**
This reverts commit e6c25770e88b3c639111491451f17a1e9e4e6881 (that reverted and backed out the patch). 

The issue was that I did not increment the `dbVersion` so the `onupgradeneeded` never updated the schema for profiles that needed to migrate.

### CODE REVIEW

**Comment by Mardak** [comment]
I didn't look at the changes, but this needs a better commit message when landing. Probably just the original commit message instead of "Revert Revert"

**Comment by as-pine-proxy** [comment]
[Treeherder: 2c2beba4945a38eb284610fa74d7b7775f9353a6](https://treeherder.mozilla.org/#/jobs?repo=pine&revision=2c2beba4945a38eb284610fa74d7b7775f9353a6)

**Comment by Mardak** [comment]
I'm trying to export, and this seems to be throwing an exception:
```
~/mozilla-central$ ./mach test all_files_referenced | grep activity-stream
 0:03.27 GECKO(8905) get db@resource://activity-stream/lib/ActivityStreamStorage.jsm:18:12
 0:03.27 GECKO(8905) getStore@resource://activity-stream/lib/ActivityStreamStorage.jsm:29:5
 0:03.27 GECKO(8905) getAll@resource://activity-stream/lib/ActivityStreamStorage.jsm:37:12
 0:03.27 GECKO(8905) _setPrerenderPref@resource://activity-stream/lib/PrefsFeed.jsm:39:34
 0:03.27 GECKO(8905) async*onAction@resource://activity-stream/lib/PrefsFeed.jsm:137:9
 0:03.27 GECKO(8905) _middleware/</<@resource://activity-stream/lib/Store.jsm:49:11
 0:03.27 GECKO(8905) Store/this[method]@resource://activity-stream/lib/Store.jsm:28:55
 0:03.27 GECKO(8905) updateTheme@resource://activity-stream/lib/ThemeFeed.jsm:51:5
 0:03.27 GECKO(8905) init@resource://activity-stream/lib/ThemeFeed.jsm:16:5
 0:03.27 GECKO(8905) onAction@resource://activity-stream/lib/ThemeFeed.jsm:57:9
 0:03.27 GECKO(8905) _middleware/</<@resource://activity-stream/lib/Store.jsm:49:11
 0:03.27 GECKO(8905) Store/this[method]@resource://activity-stream/lib/Store.jsm:28:55
 0:03.27 GECKO(8905) init@resource://activity-stream/lib/Store.jsm:136:7
 0:03.27 GECKO(8905) init@resource://activity-stream/lib/ActivityStream.jsm:275:7
 0:03.27 GECKO(8905) init@resource://gre/modules/addons/XPIProvider.jsm -> file:///Users/Ed/Development/mozilla-central/obj/dist/Nightly.app/Contents/Resources/browser/features/activity-stream@mozilla.org/bootstrap.js:64:5
 0:03.27 GECKO(8905) onBrowserReady@resource://gre/modules/addons/XPIProvider.jsm -> file:///Users/Ed/Development/mozilla-central/obj/dist/Nightly.app/Contents/Resources/browser/features/activity-stream@mozilla.org/bootstrap.js:121:3
 0:03.27 GECKO(8905) observe/<@resource://gre/modules/addons/XPIProvider.jsm -> file:///Users/Ed/Development/mozilla-central/obj/dist/Nightly.app/Contents/Resources/browser/features/activity-stream@mozilla.org/bootstrap.js:147:46
 0:03.27 GECKO(8905) JavaScript error: resource://activity-stream/lib/ActivityStreamStorage.jsm, line 19: Error: It looks like the db connection has not initialized yet. Are you use .init was called?
```

**Comment by Mardak** [comment]
Actually, that code for at.THEME_UPDATE seems to be added by #4044 @rlr?

**Pull request merged**
