### PR TITLE
Bug 1575063 - Show new topsites image icons immediately on initial "Add Top Site"

### PR DESCRIPTION
**Pull request by JeaneC**
Edit: This current fix is a no-go (data leak - see comments below)

Bug:
https://drive.google.com/file/d/1hcMJcs8gfcpEeVThy70RpxAjUuQVBMzc/view?usp=sharing

Fix:
https://drive.google.com/file/d/1lh5O1gonmDo3dq8q6lVtj1CvkAlkk0OC/view?usp=sharing

### CODE REVIEW

**Comment by Mardak** [comment]
The page shouldn't be making requests to image urls as it would leak data. The image should have been fetched and cached by the time the user has gone through the custom image dialog. If the page isn't showing the image right away, then something else has been broken in getting the images.

**Comment by Mardak** [comment]
A quick test shows latest 69 beta (b15) shows the cached custom image immediately, so something regressed in nightly 70.

**Comment by punamdahiya** [comment]
> A quick test shows latest 69 beta (b15) shows the cached custom image immediately, so something regressed in nightly 70.

I am able to replicate the issue with 69 b156 after resetting pinned pref. Tried adding topsite using image https://screenshotscdn.firefoxusercontent.com/images/bd98c6ef-0c53-4dac-902a-1efed8c21496.png

**Comment by punamdahiya** [comment]
> A quick test shows latest 69 beta (b15) shows the cached custom image immediately, so something regressed in nightly 70.

This issue replicates intermittently in 69 b15 though much more consistent in 70

**Comment by punamdahiya** [comment]
Closing PR to debug intermittent and fix as a separate PR because of concern raised https://github.com/mozilla/activity-stream/pull/5265#issuecomment-523109143

**Pull request closed without merging**
