### PR TITLE
Backport Bug 1528955 - Tab successfully pinned notification

### PR DESCRIPTION
**Pull request by rlr**
This is against master.

The changes to `lib/ASRouter.jsm` are already in central.

### CODE REVIEW

**Comment by rlr** [comment]
errr. I guess the test fixes should be in a PR to master. Fixing.

**Comment by piatra** [comment]
Backports should be against `central` branch and we then merge that into master.

**Comment by rlr** [comment]
The backport itself is already on the central branch. But it needed an update for tests to pass. So I included the merge from central and the update commit in this PR against master. I *think* that's the process from what I understood in the docs?

**Comment by k88hudson** [comment]
Looks good, I'll land this for you

**Pull request closed without merging**
