### PR TITLE
fix(metadata-store): #1012 Fix the intermittent timeout failure

### LINKED ISSUE #1012: Intermittent failure: ./test/test-MetadataStore.test_data_expiry - It should have deleted the expired page - 3 == 2
Running the jpm tests locally on my Mac, I'm occasionally seeing this failure:

```
console.info: activity-streams: executing './test/test-MetadataStore.test_data_expiry'
console.error: activity-streams: 
  fail:
  It should have deleted the expired page - 3 == 2
console.trace: activity-streams: 
_ecated/unit-test.js 108 fail
_/sdk/test/assert.js 88 fail
_/sdk/test/assert.js 123 equal
_st-MetadataStore.js 218 exports.test_data_expiry
_re/modules/Task.jsm 319 TaskImpl_run
_/Promise-backend.js 937 Handler.prototype.process
_/Promise-backend.js 816 this.PromiseWalker.walkerLoop
_/Promise-backend.js 750 this.PromiseWalker.scheduleWalkerLoop/<

console.info: activity-streams: pass: This test is done.
console.info: activity-streams: pass: There was a clean UI.
```

My guess would be there's something extra in the store that shouldn't be.

### PR DESCRIPTION
**Pull request by ncloudioj**
This fixes #1012

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-stream/1021)

### CODE REVIEW

**Comment by rlr** [comment]
changes LGTM but travis failed on different test. I restarted the tests to make sure they pass.

**Comment by rlr** [comment]
travis happy now 🚀 r+

**Comment by ncloudioj** [comment]
Thanks @rlr 👍 

For those annoy intermittent test failures, let's kill'em all 🎱

**Comment by Standard8** [comment]
@ncloudioj Thanks for fixing this!

**Comment by ncloudioj** [comment]
Thank you! @Standard8 The intermittent demon hunter 👍

**Pull request merged**
