### PR TITLE
fix(content): #833 Separator for delete is in the wrong place

### LINKED ISSUE #833: Bug 1279434 - "Delete from History" and "Dismiss" buttons from context menu are wrongly positioned
via https://bugzilla.mozilla.org/show_bug.cgi?id=1279434
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.19-dev

[Affected Platforms]:
- All Windows
- All Linux
- All Mac OS

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.19) was previously installed on a profile.
- Have two profiles: profile A has a Firefox account, profile B doesn't have a Firefox account.
- Have enough history so that the "Top Sites", "Highlights", "History" areas are populated with visited websites.

[Steps to reproduce]:
1. Open the browser with the profile A from prerequisites.
2. Open a New Tab so the Activity Stream New Tab page is displayed.
3. Move the mouse cursor over a visited item.
4. Click on "..." button.
5. Observe the context menu.
6. Open the browser with the profile B from prerequisites.
7. Open a New Tab so the Activity Stream New Tab page is displayed.
8. Move the mouse cursor over a visited item.
9. Click on "..." button.
10. Observe the context menu.

[Expected result]:
- "Delete from History" and "Dismiss" buttons are displayed under the second separator line.

[Actual result]:
- For the profile with the Firefox account, "Delete from History" and "Dismiss" buttons are displayed above the second separator line.
different context menus

### PR DESCRIPTION
**Pull request by k88hudson**
Quick fix for this one. R? @oyiptong @sarracini or @rlr?

Fixes #833 

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-stream/839)

### CODE REVIEW

**Comment by pdehaan** [comment]
From @oyiptong in IRC:

1. in the first screenshot, i can open two context menus:
    

2. in the second screenshot i see the delete separator... but no delete options:

**Comment by k88hudson** [comment]
Oops! Ok, should be all good now

**Comment by k88hudson** [comment]
I snuck in another small issue I found 🐭

**Comment by oyiptong** [comment]
r+

**Comment by pdehaan** [comment]
Not sure why Travis-CI isn't even starting these builds. 😿

**Comment by pdehaan** [comment]
I think @oyiptong already gave his blessing. Merging so we can maybe still get this in today's build.

**Pull request merged**
