### PR TITLE
chore(release): #1381 Revert  override for weightedHighlights

### PR DESCRIPTION
**Pull request by k88hudson**

### CODE REVIEW

**Comment by piatra** [comment]
Is this a prereq for releasing it as an experiment?

**Comment by ncloudioj** [comment]
@piatra Yes, we're looking to cut the release. I think you've dropped a comment about this, right?

**Comment by k88hudson** [comment]
@piatra yep! we are releasing for 1.1.5

**Comment by k88hudson** [comment]
Waiting a bit this so we still get the override on dev channel

**Pull request merged**
