### PR TITLE
feat(sections): Add section ordering, and custom sections to the pref pane

### PR DESCRIPTION
**Pull request by AdamHillier**
Move TopStories config out of TopStoriesFeed and PreferencesPane and
into SectionsManager.jsm. Underlying work for #3194.

### CODE REVIEW

**Comment by AdamHillier** [comment]
screen shot 2017-08-23 at 11 36 06 am

**Comment by as-pine-proxy** [comment]
[Treeherder: 1e9ceb526c69a9abd8654f5f6deb2ed29f9e7e35](https://treeherder.mozilla.org/#/jobs?repo=pine&revision=1e9ceb526c69a9abd8654f5f6deb2ed29f9e7e35)

**Comment by Mardak** [comment]
Treeherder seems to have started failing from this PR.

 FAIL | browser/extensions/activity-stream/test/functional/mochitest/browser_as_render.js | Uncaught exception
Should render activity stream content - timed out after 50 tries.

**Comment by Mardak** [comment]
Should we back this out so we can still export today?

**Pull request merged**
