### PR TITLE
Preparing the release of Activity Stream 1.1.9

### PR DESCRIPTION
**Pull request by ncloudioj**
Hi all,

We are now preparing the release of A-S 1.1.9. The add-on has been made available at [pre-release channel](https://moz-activity-streams-prerelease.s3.amazonaws.com/dist/latest.html). Please install it, test it, and leave the feedback, bug reports, and other inputs in this thread.

# Highlights (Changelog)
* [new] Graduated the local metadata parsing 💯 
* [fix] Optimized the webpack build to reduce the add-on size by 25% 💯 
* [fix] Various bugfixes in TabTracker, ContextMenu, and ExperimentProvider
* [fix] Cleaned up the exception reporting
* [deprecated] The forked version of simple storage
* [deprecated] The recommended related code

# Release checklist
- QA
  - [ ] @pdehaan 
  - [ ] @SoftVision
- Product
  - [ ] @nchapman 
  - [x] @aaronrbenson 
- Engineering
  - [x] @tspurway 
  - [ ] @jennchaulk 

Please use the `release/block` or `release/uplift` to label the bug reports as well as other release related issues. Once you finish the review, please check off the corresponding item in the above checklist.

*Note*: checking off the item may not work, you can either modify it in place (i.e modify `[ ]` to `[x]`), or just drop a good old `r+` comment below.

[Edit]: I've updated the version of this release to 1.1.9, since we have had a chemspill release that, unfortunately, has taken the 1.1.8. My apologies for the confusion, and we are going to fix it to avoid any further version collisions.

Thanks

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-stream/1827)

### CODE REVIEW

**Comment by dmose** [comment]
We may want to consider uplifting https://github.com/mozilla/activity-stream/commit/df7f9f65d6c3a0fa8f372a4859a694331640c702 in order to resolve the bogus telemetry data being described in #1869 (which is really just a duplicate of #1767)

**Comment by ncloudioj** [comment]
@dmose sure, I think df7f9f6 is already in this release branch.

**Comment by SoftVision-CiprianMuresan** [comment]
After running our set of [tests](https://testrail.stage.mozaws.net/index.php?/runs/view/1719&group_by=cases:section_id&group_order=asc&group_id=1144), everything looks fine, except a few things.

**New issues found**: 
1. #1884 - [Search bar] A different keyword is searched for when using a different search engine

**Known issues**:
1. From our point of view #1544 would be nice to be resolved, as new users that want to try the experiment are shown pictures of the Timeline view (which is on hold and no longer in the add-on).
2.  On the "Share" functionality, #1115 is still reproducible which is kind of easy to encounter on real life usage.

**Comment by dmose** [comment]
@ncloudioj: You're right it; it is on the release branch itself.  I was
looking at the 1.1.8 section of the "Releases" tab in the "Code" tab of
github, where there is a static tag for a commit that doesn't yet have that
commit, which is confusing.  Why do we have a static tag for the release
itself before the release has been signed off and cut?


2016-12-20 8:00 GMT-08:00 Ciprian Muresan <notifications@github.com>:

**Comment by ncloudioj** [comment]
@dmose Unfortunately, it's kinda confusing :/. Co's we had a chemspill release (1.1.8) after we cut the release-1.1.8 branch, that being said, this release should be actually tagged as 1.1.9.

For next release, we will be bumping up the minor version instead of the patch one, to avoid the version conflict as mentioned above.

**Comment by dmose** [comment]
@nanjiang: makes sense.  Thanks for the clarification, and glad we're
tweaking process!

2016-12-20 8:15 GMT-08:00 Nan Jiang <notifications@github.com>:

**Comment by jaredkerim** [comment]
Please back this commit out of this release:

https://github.com/mozilla/activity-stream/commit/1890042705cfe1a00152b43163c1b2524ab463a9

and block the release on this issue:

https://github.com/mozilla/activity-stream/issues/1897

**Comment by ncloudioj** [comment]
Closing this as we've cut the release for 1.1.9. The changelog and new tag have been cherry-picked to the master branch.

**Pull request closed without merging**
