### PR TITLE
chore(storybook): support building of storybooks for PRs by storybook.io

### PR DESCRIPTION
**Pull request by dmose**
Once this lands, we'll be able to get automatically built storybooks.  Click on the last "View Deployment" button in https://github.com/dmose/activity-stream/pull/6 to see an example.

r? @Mardak

### CODE REVIEW

**Comment by Mardak** [comment]
What am I looking for in dmose#6? Clicking on either deployment results in `Internal server error [500]`

**Comment by dmose** [comment]
@Mardak They both seem to be working for me now.  I suspect they had some sort of infrastructure issue that they've since fixed.

You should see something like this:

screen shot 2016-09-30 at 06 41 49

**Comment by dmose** [comment]
So it turns out that at this moment, you need to log in to storybooks.io using your github account to avoid the error.  I've pinged their support about this.

**Comment by Mardak** [comment]
Got things working by logging in with Google (so it only requests email address instead of read/write access to github repositories)

**Pull request merged**
