### PR TITLE
Preparing the release of Activity Stream v1.4.0

### PR DESCRIPTION
**Pull request by sarracini**
Hi all,

We are now preparing the release of A-S 1.4.0. The add-on has been made available at [pre-release channel](https://moz-activity-streams-prerelease.s3.amazonaws.com/dist/latest.html). Please install it, test it, and leave the feedback, bug reports, and other inputs in this thread.

Highlights&Changelog:

# Release checklist
- QA
  - [ ] @pdehaan 
  - [ ] @SoftVision
- Product
  - [ ] @nchapman 
  - [ ] @aaronrbenson 
- Engineering
  - [ ] @tspurway 
  - [ ] @jennchaulk 

Please use the `release/block` or `release/uplift` to label the bug reports as well as other release related issues. Once you finish the review, please check off the corresponding item in the above checklist.

*Note*: checking off the item may not work, you can either modify it in place (i.e modify `[ ]` to `[x]`), or just drop a good old `r+` comment below.

*Note*: release highlights and the changelog will be attached shortly.

Thanks

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-stream/2107)

### CODE REVIEW

**Comment by aaronrbenson** [comment]
Should the What's this links be showing up? I thought we had a PR to remove these?

**Comment by aaronrbenson** [comment]
Kottke favicon card isn't getting rounded corners for some reason. Others seem good.
screen shot 2017-02-03 at 9 49 56 am

**Comment by Softvision-VladBacia** [comment]
After running our set of tests, everything looks fine, except a few things.

**New issues found:**
* [ ] #2125 - site-icon-fallback has a bigger dimension than the Top Sites card

**Known issues:**
From our point of view #1544 would be nice to be resolved, as new users that want to try the experiment are shown pictures of the Timeline view (which is on hold and no longer in the add-on). Also, #2042 breaks the search functionality if the user uses the browser "Back" button to return to AS New Tab page after a refresh.
On the "Share" functionality, #1115 is still reproducible which is kind of easy to encounter in real life usage.

**Comment by rlr** [comment]
^ I cherry-picked the commit that disables the screenshot experiment from the release-1.3.0 branch.

**Pull request merged**
