### PR TITLE
Bug 1543436 - Updated usesFirefoxSync to use UIState

### PR DESCRIPTION
**Pull request by dannycoates**
Testing the water with this one. @vbudhram @piatra f?

### CODE REVIEW

**Comment by piatra** [comment]
Looks good to me. What happens on startup? You mentioned some delay before `state` is "accurate". If a user is signed in but `UIState` is not up to date yet then the getter retuns `false` and they see a FxA snippet?

**Comment by dannycoates** [comment]
The pref is good enough at startup. I've updated the code to use that until UIState is ready.

**Comment by piatra** [comment]
Then this looks good to me. You might need to update the mochitests as well 
https://github.com/mozilla/activity-stream/blob/48d1f4c662c7f086ee9691272c9a0e79203b3c0d/test/browser/browser_asrouter_targeting.js#L142-L150
Right now it's setting the pref.

**Comment by piatra** [comment]
We should add a new tests that checks the `STATUS_LOGIN_FAILED` scenario (`usesFirefoxSync` is `false` and no messages are returned).
I think we can simply overwrite `UIState`:
```javascript
UIState.get = () => ({status: UIState.STATUS_LOGIN_FAILED});
```
As long as we restore it after the tests ends. If you switch your PR to `Ready for review` you can have the automated tests run on your PR without having to build it yourself locally.

**Comment by piatra** [comment]
The existing approach is fine for the use case so we're not going to update this.

**Pull request closed without merging**
