### PR TITLE
fix(addon): #518 Fix Embedly proxy receiving null URLs

### PR DESCRIPTION
**Pull request by sarracini**
Working on a test for it now, but this fixes the null problem. yay!

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-stream/697)

### CODE REVIEW

**Comment by sarracini** [comment]
what's going on with travis? https://travis-ci.org/mozilla/activity-stream/builds/130038880#L419 
this doesn't look like it was related to my patch?

**Comment by oyiptong** [comment]
That's the error:

```
console.error: activity-streams: 

  fail:

  undefined - "http://localhost:8199/dummy-activitystreams.html#/timeline/bookmarks" == "about:privatebrowsing"

console.trace: activity-streams: 

_ecated/unit-test.js 108 fail

_/sdk/test/assert.js 88 fail

_/sdk/test/assert.js 123 equal

_private-browsing.js 32 exports["test activity stream doesn't load in private windows"]/</<.onReady

_s/sdk/event/core.js 112 emitOnObject

_s/sdk/event/core.js 89 emit

_tabs/tab-firefox.js 264 tabEmit

_tabs/tab-firefox.js 328 tabEventListener

_tabs/tab-firefox.js 347 

_s/sdk/event/core.js 112 emitOnObject

_s/sdk/event/core.js 89 emit

_s/sdk/event/core.js 112 emitOnObject

_s/sdk/event/core.js 89 emit

_s/sdk/event/core.js 123 emitOnObject

_s/sdk/event/core.js 89 emit

_dk/remote/parent.js 96 messageReceived
```

perhaps this an intermittent issue? otherwise this patch may have caused the test to fail somehow.
In any case @rlr had been working on the private browsing patch and could help if you need it.

**Comment by rlr** [comment]
awesomesauce 👍  R+!

We might want to refactor this later so that `asyncSaveLinks()` calls `processLinks()` so that we don't have this issue of forgetting. But I didn't look to see if that would break something else. Something to consider.

**Comment by rlr** [comment]
I'll take a look at that intermittent failure to see if I can find what is going on. Also, are we releasing this quickly?

**Comment by sarracini** [comment]
I agree about the refactoring. 
We're going to deploy at the end of the day, with this change in it.

**Comment by oyiptong** [comment]
There should not be any rush to release things quickly because we can deploy literally any time.

However, if this is merged today, it will go out with this afternoon's deploy

**Pull request merged**
