### PR TITLE
chore(lint): Turn on already passing eslint rules.

### PR DESCRIPTION
**Pull request by Mardak**
I know this conflicts with #961 but this doesn't require any code changes. Just `.eslintrc` additions. r?@pdehaan

I basically copied over `loop`'s `.eslintrc` https://github.com/mozilla/loop/blob/master/.eslintrc and removed rules that didn't pass for `activity-stream` and `eslint v2.2.0` (where `loop` has stuff up to `v2.13.1`)

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-stream/1035)

### CODE REVIEW

**Comment by pdehaan** [comment]
I love adding rules! 😍 

Before we R+ this, do you mind bumping the ancient **eslint** and **eslint-plugin-react** dev dependencies (`$ npm i eslint@latest eslint-plugin-react@latest -D`) and seeing if the errors make sense? I'm seeing 30 errors when bumping to latest versions, but I'm not a generator/yield kind of guy, so I'm not sure if those are valid errors, or something that doesn't apply to us in our Firefox add-on scope (but we can always just disable those rules). Also seeing 2 errors for `react/self-closing-comp` which may be worth investigating.

Oh, plus this warning seems new and related to bumping the dependency versions:

> _"The react/wrap-multilines rule is deprecated. Please use the react/jsx-wrap-multilines rule instead."_

```sh
$ npm run test:lint

> activity-streams@1.1.1 test:lint /Users/pdehaan/dev/github/mozilla/activity-streams
> eslint . && jscs . && sass-lint -v -q

The react/wrap-multilines rule is deprecated. Please use the react/jsx-wrap-multilines rule instead.

/Users/pdehaan/dev/github/mozilla/activity-streams/content-src/components/MediaPreview/MediaPreview.js
  27:17  error  Empty components are self-closing  react/self-closing-comp

/Users/pdehaan/dev/github/mozilla/activity-streams/content-src/components/Search/Search.js
  286:22  error  Empty components are self-closing  react/self-closing-comp

/Users/pdehaan/dev/github/mozilla/activity-streams/lib/RecommendationProvider.js
  125:43  error  This generator function does not have 'yield'  require-yield

/Users/pdehaan/dev/github/mozilla/activity-streams/lib/SearchProvider.js
   44:18  error  This generator function does not have 'yield'  require-yield
  137:36  error  This generator function does not have 'yield'  require-yield

/Users/pdehaan/dev/github/mozilla/activity-streams/test/test-ActivityStreams-home-page.js
  8:71  error  This generator function does not have 'yield'  require-yield

/Users/pdehaan/dev/github/mozilla/activity-streams/test/test-Memoizer.js
  138:17  error  This generator function does not have 'yield'  require-yield
  144:16  error  This generator function does not have 'yield'  require-yield

/Users/pdehaan/dev/github/mozilla/activity-streams/test/test-MetadataStore.js
  221:34  error  This generator function does not have 'yield'  require-yield

/Users/pdehaan/dev/github/mozilla/activity-streams/test/test-PerfMeter.js
  220:39  error  This generator function does not have 'yield'  require-yield

/Users/pdehaan/dev/github/mozilla/activity-streams/test/test-PlacesProvider-blockedURLs.js
   7:34  error  This generator function does not have 'yield'  require-yield
  27:45  error  This generator function does not have 'yield'  require-yield
  59:17  error  This generator function does not have 'yield'  require-yield

/Users/pdehaan/dev/github/mozilla/activity-streams/test/test-PreviewProvider.js
   71:28  error  This generator function does not have 'yield'  require-yield
  103:30  error  This generator function does not have 'yield'  require-yield
  141:30  error  This generator function does not have 'yield'  require-yield
  163:28  error  This generator function does not have 'yield'  require-yield
  305:17  error  This generator function does not have 'yield'  require-yield
  327:16  error  This generator function does not have 'yield'  require-yield

/Users/pdehaan/dev/github/mozilla/activity-streams/test/test-RecommendationProvider.js
   71:37  error  This generator function does not have 'yield'  require-yield
   92:41  error  This generator function does not have 'yield'  require-yield
  107:43  error  This generator function does not have 'yield'  require-yield
  129:38  error  This generator function does not have 'yield'  require-yield
  150:17  error  This generator function does not have 'yield'  require-yield
  164:16  error  This generator function does not have 'yield'  require-yield

/Users/pdehaan/dev/github/mozilla/activity-streams/test/test-TabTracker.js
  545:33  error  This generator function does not have 'yield'  require-yield

/Users/pdehaan/dev/github/mozilla/activity-streams/test/test-TelemetrySender.js
  50:38  error  This generator function does not have 'yield'  require-yield
  65:17  error  This generator function does not have 'yield'  require-yield

/Users/pdehaan/dev/github/mozilla/activity-streams/test/test-TippyTopProvider.js
   5:41  error  This generator function does not have 'yield'  require-yield
  22:48  error  This generator function does not have 'yield'  require-yield

✖ 30 problems (30 errors, 0 warnings)
```

**Comment by pdehaan** [comment]
Also, looking at https://github.com/yannickcr/eslint-plugin-react#recommended, we may want to extend the recommended [**eslint-plugin-react** recommended rules](https://github.com/yannickcr/eslint-plugin-react/blob/1ab2eec47397b028da6bef390388678cff8c5970/index.js#L68-L90) while we're at it:

```yaml
extends:
  - eslint:recommended
  - plugin:react/recommended
```

**Comment by Mardak** [comment]
I believe @Standard8 has a branch to get things ready for updating eslint version https://github.com/mozilla/activity-stream/compare/master...Standard8:npm-eslint

Turning on `plugin:react/recommended` will require a lot of code changes in particular for `propTypes`.

There are some additional already passing rules that could be turned on of `eslint` was updated, but we can do that in a separate PR that has code changes fixing `require-yield` issues.

For the additional rules on newer version:
```json
"no-confusing-arrow": [2, {"allowParens": true}],
"no-unsafe-finally": 2,
"no-useless-computed-key": 2,
"no-useless-escape": 2,
```

**Comment by pdehaan** [comment]
@Mardak @Standard8 Great work!

I'm OK to merge this whenever, as long as we can get the core **eslint** and **eslint-plugin-react** dependencies updated [in a future PR] and make sure everything passes and is still kosher. 👍

**Pull request merged**
