### PR TITLE
Bug 1574995 - Update Firefox workmark for the New Tab page

### PR DESCRIPTION
**Pull request by shorlander**
Update:
- firefox-wordmark.svg
- Adjust sizing

### CODE REVIEW

**Comment by shorlander** [comment]
@ScottDowne would you be able to review this please?

@k88hudson suggested you would be a good person to ask. 

Thank you!

**Comment by ScottDowne** [comment]
Looking

**Comment by ScottDowne** [comment]
@k88hudson I'm confused, the pull request here says it's on shorlander/master. But if I look closer at shorlander's repo, it actually says it's on shorlander/activity-stream-1

**Comment by ScottDowne** [comment]
Found it, there is shorlander/activity-stream and shorlander/activity-steam-1, we want shorlander/activity-stream-1

**Comment by ScottDowne** [comment]
@k88hudson I don't know anything about svg image optimization, is there anything I can do to verify that? Otherwise this seems fine, and the old svg compared to the new svg look like nothing be harmless changes.

**Comment by shorlander** [comment]
> @k88hudson I don't know anything about svg image optimization, is there anything I can do to verify that? Otherwise this seems fine, and the old svg compared to the new svg look like nothing be harmless changes.

I did run it through SVGO already :)

> Found it, there is shorlander/activity-stream and shorlander/activity-steam-1, we want shorlander/activity-stream-1

Sorry about that, I already had an activity-repo for prototyping from a long time ago.

**Pull request merged**
